import LeanCondensedMatter.SecondQuantization.Fermionic.Diagrammatics.TwoPointDiagramExpansion.InteractionVertexRelabelCovariance
import LeanCondensedMatter.SecondQuantization.Fermionic.Diagrammatics.TwoPointDiagramExpansion.InteractionVertexRelabelIntegralCovariance
import LeanCondensedMatter.SecondQuantization.Fermionic.Diagrammatics.TwoPointDiagramExpansion.MixedComponentShuffleIntegrability
import LeanCondensedMatter.SecondQuantization.Fermionic.Diagrammatics.TwoPointDiagramExpansion.MixedComponentDysonIntegral
import LeanCondensedMatter.SecondQuantization.Fermionic.Diagrammatics.TwoPointDiagramExpansion.DiagramSumIntegral
import LeanCondensedMatter.SecondQuantization.Fermionic.Diagrammatics.TwoPointDiagramExpansion.MixedExternalPositions
import LeanCondensedMatter.SecondQuantization.Fermionic.Diagrammatics.TwoPointDiagramExpansion.ComponentAmplitudeFactorization

set_option linter.style.header false

/-!
# Fermionic two-point diagram expansion

Finite-mode imaginary-time two-point Wick diagrams with quartic interaction vertices: mixed-time
ordering and flattening, fixed-external amplitudes, external/vacuum component restriction and
factorization, measurable and integrable component-local factors, ordered-simplex component
shuffles, interaction-slot relabeling, and the exchange of the finite diagram sum with the
ordered-simplex integral. The umbrella exports authoritative owner modules rather than the
proof-stage transport chain used internally.
-/
