import LeanCondensedMatter.SecondQuantization.Common.OneParticleSpace
import LeanCondensedMatter.SecondQuantization.Common.Statistics
import LeanCondensedMatter.SecondQuantization.Common.OccupationBasis
import LeanCondensedMatter.SecondQuantization.Common.AlgebraicFock
import LeanCondensedMatter.SecondQuantization.Common.FiniteOperatorIntegral
import LeanCondensedMatter.SecondQuantization.Common.ParticleNumberSelectionRule
import LeanCondensedMatter.SecondQuantization.Common.ExchangeCommutator
import LeanCondensedMatter.SecondQuantization.Common.ExchangeAlgebra
import LeanCondensedMatter.SecondQuantization.Common.TimeOrdering
import LeanCondensedMatter.SecondQuantization.Common.DiagonalEvolution
import LeanCondensedMatter.SecondQuantization.Common.NormalizedOperatorFunctional
import LeanCondensedMatter.SecondQuantization.Common.WeightedDiagonalFunctional
import LeanCondensedMatter.SecondQuantization.Common.KMSRotation
import LeanCondensedMatter.SecondQuantization.Common.QuarticVertexLabel
import LeanCondensedMatter.SecondQuantization.Common.QuarticLeg
import LeanCondensedMatter.SecondQuantization.Common.QuarticDiagram
import LeanCondensedMatter.SecondQuantization.Common.QuarticDiagramConnected
import LeanCondensedMatter.SecondQuantization.Common.QuarticDiagramComponentPartition
import LeanCondensedMatter.SecondQuantization.Common.QuarticDiagramComponentRestriction
import LeanCondensedMatter.SecondQuantization.Common.QuarticDiagramComponentConnected
import LeanCondensedMatter.SecondQuantization.Common.QuarticDiagramReassemble
import LeanCondensedMatter.SecondQuantization.Common.QuarticDiagramReassembleComponentPartitionEq
import LeanCondensedMatter.SecondQuantization.Common.QuarticDiagramReassembleRestrictComponent
import LeanCondensedMatter.SecondQuantization.Common.QuarticDiagramReassembleDecompose
import LeanCondensedMatter.SecondQuantization.Common.QuarticDiagramComponentDecompositionEquiv
import LeanCondensedMatter.SecondQuantization.Common.BlochDeDominicis

set_option linter.style.header false
/-!
# Statistics-independent second quantization

Umbrella module for the shared bosonic and fermionic layer.
-/
