import LeanCondensedMatter.QuantumTheory.ConservationLaw.HeisenbergTransport
import Mathlib.Tactic.Module

set_option linter.style.header false

/-!
# Conventional current as a specialization of generalized transport

Suppose a differential-like test `d f` is localized by `N`, and the Heisenberg motion of
localization has the first-order form

```text
δₕ(M f) = 1/2 {N (d f), v}.
```

If `N α` commutes with the transported one-body quantity `m`, then the generalized transport
functional has the zeroth-order operator-local pairing

```text
Φₘ(f) = 1/2 {N (d f), jᵐ},

jᵐ = 1/2 {v, m}.
```

Thus `jᵐ` is a derived `LocalCurrentDensityRepresentation`. The commutation hypothesis is explicit,
so differential or nonlocal quantities such as continuum orbital angular momentum are not forced
through this conventional formula.
-/

namespace QuantumTheory
namespace ConservationLaw

variable {Test OneForm : Type*}
variable [AddCommGroup Test] [Module ℂ Test]
variable [AddCommGroup OneForm] [Module ℂ OneForm]
variable (V : Type*) [AddCommGroup V] [Module ℂ V]

/-- The conventional one-body current operator `jᵐ = 1/2 {v, m}`. -/
noncomputable def conventionalCurrent
    (velocity m : V →ₗ[ℂ] V) : V →ₗ[ℂ] V :=
  _root_.ConservationLaw.symmetrizedProduct velocity m

@[simp]
theorem conventionalCurrent_smul_id
    (velocity : V →ₗ[ℂ] V) (q : ℂ) :
    conventionalCurrent V velocity (q • LinearMap.id) = q • velocity := by
  exact _root_.ConservationLaw.symmetrizedProduct_smul_id velocity q

@[simp]
theorem conventionalCurrent_id
    (velocity : V →ₗ[ℂ] V) :
    conventionalCurrent V velocity LinearMap.id = velocity := by
  simpa using conventionalCurrent_smul_id V velocity (1 : ℂ)

/-- Reassociation identity behind the conventional-current formula. -/
theorem symmetrizedProduct_nested_eq_of_commutes
    (localizer velocity m : V →ₗ[ℂ] V)
    (hcomm : _root_.ConservationLaw.linearCommutator localizer m = 0) :
    _root_.ConservationLaw.symmetrizedProduct
        (_root_.ConservationLaw.symmetrizedProduct localizer velocity) m =
      _root_.ConservationLaw.symmetrizedProduct localizer
        (_root_.ConservationLaw.symmetrizedProduct velocity m) := by
  apply LinearMap.ext
  intro x
  have hlocalizer (y : V) : localizer (m y) = m (localizer y) := by
    have h := congrArg (fun T : V →ₗ[ℂ] V => T y) hcomm
    have hzero : localizer (m y) - m (localizer y) = 0 := by
      simpa [_root_.ConservationLaw.linearCommutator] using h
    exact sub_eq_zero.mp hzero
  simp [_root_.ConservationLaw.symmetrizedProduct, hlocalizer]
  module

/-- A one-form-like test is paired with a one-body current operator by symmetric localization,
`(j, α) ↦ 1/2 {N α, j}`. -/
noncomputable def operatorLocalCurrentPairing
    (N : OneForm →ₗ[ℂ] (V →ₗ[ℂ] V)) :
    _root_.ConservationLaw.LocalCurrentPairing
      (𝕜 := ℂ)
      (OneForm := OneForm)
      (Obs := V →ₗ[ℂ] V)
      (CurrentDensity := V →ₗ[ℂ] V) where
  toFun := fun current => (symmetrizedProductRightLinear V current).comp N
  map_add' := by
    intro j₁ j₂
    apply LinearMap.ext
    intro α
    apply LinearMap.ext
    intro x
    simp [symmetrizedProductRightLinear, _root_.ConservationLaw.symmetrizedProduct]
    module
  map_smul' := by
    intro c j
    apply LinearMap.ext
    intro α
    apply LinearMap.ext
    intro x
    simp [symmetrizedProductRightLinear, _root_.ConservationLaw.symmetrizedProduct]
    module

@[simp]
theorem operatorLocalCurrentPairing_apply
    (N : OneForm →ₗ[ℂ] (V →ₗ[ℂ] V))
    (current : V →ₗ[ℂ] V) (α : OneForm) :
    operatorLocalCurrentPairing V N current α =
      _root_.ConservationLaw.symmetrizedProduct (N α) current :=
  rfl

/-- Flux functional generated by velocity and localization of a one-form-like test. -/
noncomputable def velocityLocalizationFlux
    (velocity : V →ₗ[ℂ] V)
    (N : OneForm →ₗ[ℂ] (V →ₗ[ℂ] V)) :
    OneForm →ₗ[ℂ] (V →ₗ[ℂ] V) :=
  (symmetrizedProductRightLinear V velocity).comp N

@[simp]
theorem velocityLocalizationFlux_apply
    (velocity : V →ₗ[ℂ] V)
    (N : OneForm →ₗ[ℂ] (V →ₗ[ℂ] V)) (α : OneForm) :
    velocityLocalizationFlux V velocity N α =
      _root_.ConservationLaw.symmetrizedProduct (N α) velocity :=
  rfl

/-- Conventional current supplies a local current-density representation whenever the Heisenberg
localization transport is first-order in `d` and the localized one-form operators commute with the
transported quantity. -/
noncomputable def conventionalCurrentRepresentation
    (ℏ : ℝ) (h : V →ₗ[ℂ] V)
    (M : Test →ₗ[ℂ] (V →ₗ[ℂ] V))
    (m velocity : V →ₗ[ℂ] V)
    (d : Test →ₗ[ℂ] OneForm)
    (N : OneForm →ₗ[ℂ] (V →ₗ[ℂ] V))
    (hvelocity : _root_.ConservationLaw.FactorsThroughDifferential d
      (heisenbergLocalizationFunctional V ℏ h M)
      (velocityLocalizationFlux V velocity N))
    (hcomm : ∀ α, _root_.ConservationLaw.linearCommutator (N α) m = 0) :
    _root_.ConservationLaw.LocalCurrentDensityRepresentation
      d
      (heisenbergTransportFunctional V ℏ h M m)
      (operatorLocalCurrentPairing V N) where
  currentDensity := conventionalCurrent V velocity m
  represents := by
    intro f
    rw [heisenbergTransportFunctional_eq_symmetrizedProductRight_comp]
    simp only [LinearMap.comp_apply]
    rw [hvelocity f]
    simpa [velocityLocalizationFlux, operatorLocalCurrentPairing, conventionalCurrent] using
      symmetrizedProduct_nested_eq_of_commutes V (N (d f)) velocity m (hcomm (d f))

@[simp]
theorem conventionalCurrentRepresentation_currentDensity
    (ℏ : ℝ) (h : V →ₗ[ℂ] V)
    (M : Test →ₗ[ℂ] (V →ₗ[ℂ] V))
    (m velocity : V →ₗ[ℂ] V)
    (d : Test →ₗ[ℂ] OneForm)
    (N : OneForm →ₗ[ℂ] (V →ₗ[ℂ] V))
    (hvelocity : _root_.ConservationLaw.FactorsThroughDifferential d
      (heisenbergLocalizationFunctional V ℏ h M)
      (velocityLocalizationFlux V velocity N))
    (hcomm : ∀ α, _root_.ConservationLaw.linearCommutator (N α) m = 0) :
    (conventionalCurrentRepresentation V ℏ h M m velocity d N hvelocity hcomm).currentDensity =
      conventionalCurrent V velocity m :=
  rfl

end ConservationLaw
end QuantumTheory
