import LeanCondensedMatter.Transport.ConductivityNormalization
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.SpectralFrequencyResponse

set_option linter.style.header false

/-!
# Fermionic finite-volume directional conductivity

The representation-independent electric-field conversion and finite-volume normalization now live
in `QuantumTheory.Transport.ConductivityNormalization`. This module retains only the finite
fermionic directional realization: it applies that canonical normalization to the total directional
current response generated by a uniform Peierls vector-potential source.

The concrete slice uses the full finite fermionic Fock space. Boundary conditions and geometry are
encoded by the finite site type, hopping amplitudes, and `LatticeGeometry`; no infinite-volume trace
per unit volume or equivalence of electromagnetic gauges is claimed. The limits `η → 0⁺` and
`ω → 0` remain separate and untaken.
-/

namespace SecondQuantization
namespace Fermionic
namespace Transport

open Lattice
open QuantumTheory.LinearResponse QuantumTheory.Transport

noncomputable section

variable {Site E : Type*}
variable [LinearOrder Site] [Fintype Site]
variable [AddCommGroup E] [Module ℝ E]

/-- Finite-observation-time, finite-volume regularized conductivity. -/
noncomputable def finiteTimeAdiabaticDirectionalConductivity
    (volume : QuantumTheory.Transport.PositiveVolume)
    (system : BoundedFreeSystem (FiniteLatticeHilbertFock Site))
    (expectation : NormalizedExpectation (FiniteLatticeHilbertFock Site))
    (geometry : LatticeGeometry Site E) (direction : E →ₗ[ℝ] ℝ)
    (K : LocallyFiniteHopping Site) (q ω η T : ℝ) : ℂ :=
  finiteVolumeConductivityFromVectorPotential volume ω η
    (finiteTimeAdiabaticDirectionalCoefficient
      system expectation geometry direction K q ω η T)

/-- Infinite-observation-time, finite-volume regularized conductivity at fixed `ω` and `η`. -/
noncomputable def infiniteTimeAdiabaticDirectionalConductivity
    (volume : QuantumTheory.Transport.PositiveVolume)
    (system : BoundedFreeSystem (FiniteLatticeHilbertFock Site))
    (expectation : NormalizedExpectation (FiniteLatticeHilbertFock Site))
    (geometry : LatticeGeometry Site E) (direction : E →ₗ[ℝ] ℝ)
    (K : LocallyFiniteHopping Site) (q ω η : ℝ) : ℂ :=
  finiteVolumeConductivityFromVectorPotential volume ω η
    (infiniteTimeAdiabaticDirectionalCoefficient
      system expectation geometry direction K q ω η)

/-- Stationarity and `η > 0` give the observation-time limit for the explicitly normalized
finite-volume conductivity. -/
theorem hasInfiniteObservationTimeLimit_directionalConductivity_of_stationary_pos
    (volume : QuantumTheory.Transport.PositiveVolume)
    (system : BoundedFreeSystem (FiniteLatticeHilbertFock Site))
    (expectation : NormalizedExpectation (FiniteLatticeHilbertFock Site))
    (hstationary : IsStationary system expectation)
    (geometry : LatticeGeometry Site E) (direction : E →ₗ[ℝ] ℝ)
    (K : LocallyFiniteHopping Site) (q ω η : ℝ) (hη : 0 < η) :
    HasInfiniteObservationTimeLimit
      (finiteTimeAdiabaticDirectionalConductivity volume
        system expectation geometry direction K q ω η)
      (infiniteTimeAdiabaticDirectionalConductivity volume
        system expectation geometry direction K q ω η) := by
  have hlimit := hasInfiniteObservationTimeLimit_directional_of_stationary_pos
    system expectation hstationary geometry direction K q ω η hη
  unfold HasInfiniteObservationTimeLimit at hlimit ⊢
  change Filter.Tendsto
    (fun T : ℝ =>
      finiteTimeAdiabaticDirectionalCoefficient
          system expectation geometry direction K q ω η T *
        finiteVolumeConductivityNormalization volume ω η)
    Filter.atTop
    (nhds
      (infiniteTimeAdiabaticDirectionalCoefficient
          system expectation geometry direction K q ω η *
        finiteVolumeConductivityNormalization volume ω η))
  exact hlimit.mul
    (tendsto_const_nhds :
      Filter.Tendsto
        (fun _ : ℝ => finiteVolumeConductivityNormalization volume ω η)
        Filter.atTop
        (nhds (finiteVolumeConductivityNormalization volume ω η)))

variable {ι : Type*}

/-- The finite pure-point conductivity is the Lehmann current response plus contact response,
multiplied by the explicit volume and electric-field normalization. -/
theorem infiniteTimeAdiabaticDirectionalConductivity_purePoint_eq_finite_sum
    [Fintype ι]
    (volume : QuantumTheory.Transport.PositiveVolume)
    (system : BoundedFreeSystem (FiniteLatticeHilbertFock Site))
    (data : PurePointLehmannData system ι)
    (geometry : LatticeGeometry Site E) (direction : E →ₗ[ℝ] ℝ)
    (K : LocallyFiniteHopping Site) (q ω η : ℝ) (hη : 0 < η) :
    infiniteTimeAdiabaticDirectionalConductivity volume
        system (purePointNormalizedExpectation system data)
          geometry direction K q ω η =
      ((∑ mn : ι × ι,
        lehmannTerm system.hbar ω η
          (data.energy mn.1 - data.energy mn.2)
          (purePointTransitionWeight system data
            (boundedDirectionalCurrent geometry direction
              (system.hbar : ℂ) (q : ℂ) K)
            (boundedDirectionalCurrent geometry direction
              (system.hbar : ℂ) (q : ℂ) K) mn)) +
        purePointNormalizedExpectation system data
          (boundedDirectionalContact geometry direction
            (system.hbar : ℂ) (q : ℂ) K)) *
        finiteVolumeConductivityNormalization volume ω η := by
  rw [infiniteTimeAdiabaticDirectionalConductivity]
  rw [finiteVolumeConductivityFromVectorPotential]
  rw [infiniteTimeAdiabaticDirectionalCoefficient_purePoint_eq_finite_sum
    system data geometry direction K q ω η hη]

/-- The finite-time conductivity converges directly to the normalized finite Lehmann sum plus
contact term. -/
theorem hasInfiniteObservationTimeLimit_directionalConductivity_purePoint_finite_sum
    [Fintype ι]
    (volume : QuantumTheory.Transport.PositiveVolume)
    (system : BoundedFreeSystem (FiniteLatticeHilbertFock Site))
    (data : PurePointLehmannData system ι)
    (geometry : LatticeGeometry Site E) (direction : E →ₗ[ℝ] ℝ)
    (K : LocallyFiniteHopping Site) (q ω η : ℝ) (hη : 0 < η) :
    HasInfiniteObservationTimeLimit
      (finiteTimeAdiabaticDirectionalConductivity volume
        system (purePointNormalizedExpectation system data)
          geometry direction K q ω η)
      (((∑ mn : ι × ι,
        lehmannTerm system.hbar ω η
          (data.energy mn.1 - data.energy mn.2)
          (purePointTransitionWeight system data
            (boundedDirectionalCurrent geometry direction
              (system.hbar : ℂ) (q : ℂ) K)
            (boundedDirectionalCurrent geometry direction
              (system.hbar : ℂ) (q : ℂ) K) mn)) +
        purePointNormalizedExpectation system data
          (boundedDirectionalContact geometry direction
            (system.hbar : ℂ) (q : ℂ) K)) *
        finiteVolumeConductivityNormalization volume ω η) := by
  have hlimit := hasInfiniteObservationTimeLimit_directionalConductivity_of_stationary_pos
    volume system (purePointNormalizedExpectation system data)
      (isStationary_purePointNormalizedExpectation system data)
      geometry direction K q ω η hη
  rw [infiniteTimeAdiabaticDirectionalConductivity_purePoint_eq_finite_sum
    volume system data geometry direction K q ω η hη] at hlimit
  exact hlimit

end
end Transport
end Fermionic
end SecondQuantization
