import LeanCondensedMatter.SecondQuantization.Fermionic.Lattice.Spinful
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.ConventionalCurrentResponse

set_option linter.style.header false

/-!
# Finite spin-current / electric-source cross response

This module gives the first concrete generalized-current response required by issue #1159 Q7. The
one-particle space is the finite spinful lattice `Site × Fin 2`. Its measured spin current is the
conventional current associated with the diagonal internal spin operator,

```text
J^(S_z) = dΓ( 1/2 {v, S_z} ),
```

transported to the bounded finite-lattice Hilbert realization. The source is an ordinary electric
bond current, so the response kernel is genuinely mixed:

```text
χᴿ_{J^(S_z), J^charge_{u→v}}.
```

No equality between spin current and charge current is assumed. The velocity is supplied as a
one-particle operator so later finite Rashba/Dirac models can instantiate it with the velocity derived
from their Hamiltonian. Conductivity normalization and source-dependent contact terms remain separate
from this causal cross-response kernel.
-/

namespace SecondQuantization
namespace Fermionic
namespace Transport

open Lattice

noncomputable section

variable {Site : Type*} [LinearOrder Site] [Fintype Site]

/-- Bounded conventional spin-z current on the finite spinful lattice. -/
noncomputable def boundedSpinZCurrent
    (velocity : LatticeState (SpinfulSite Site) →ₗ[ℂ] LatticeState (SpinfulSite Site))
    (spinScale : ℂ) :
    FiniteLatticeHilbertFock (SpinfulSite Site) →L[ℂ]
      FiniteLatticeHilbertFock (SpinfulSite Site) :=
  boundedConventionalCurrent velocity (spinZOneBody spinScale)

/-- Retarded response of a concrete finite spin-z current to an electric bond-current source.

The measured observable and source are intentionally distinct. The source carries electric charge
`q`, while the measured current is generated by the internal spin operator `S_z`. -/
noncomputable def boundedSpinZCurrentBondSourceRetardedSusceptibility
    (system : QuantumTheory.LinearResponse.BoundedFreeSystem
      (FiniteLatticeHilbertFock (SpinfulSite Site)))
    (expectation : QuantumTheory.LinearResponse.NormalizedExpectation
      (FiniteLatticeHilbertFock (SpinfulSite Site)))
    (velocity : LatticeState (SpinfulSite Site) →ₗ[ℂ] LatticeState (SpinfulSite Site))
    (spinScale ℏ q : ℂ)
    (K : LocallyFiniteHopping (SpinfulSite Site))
    (u v : SpinfulSite Site) (t s : ℝ) : ℂ :=
  boundedConventionalCurrentRetardedSusceptibility system expectation
    velocity (spinZOneBody spinScale)
    (boundedBondCurrent ℏ q K u v) t s

/-- The mixed spin/electric response is exactly the generic measured-current/source Kubo adapter
specialized to the concrete bounded spin-z current and electric bond source. -/
theorem boundedSpinZCurrentBondSourceRetardedSusceptibility_eq_generic
    (system : QuantumTheory.LinearResponse.BoundedFreeSystem
      (FiniteLatticeHilbertFock (SpinfulSite Site)))
    (expectation : QuantumTheory.LinearResponse.NormalizedExpectation
      (FiniteLatticeHilbertFock (SpinfulSite Site)))
    (velocity : LatticeState (SpinfulSite Site) →ₗ[ℂ] LatticeState (SpinfulSite Site))
    (spinScale ℏ q : ℂ)
    (K : LocallyFiniteHopping (SpinfulSite Site))
    (u v : SpinfulSite Site) (t s : ℝ) :
    boundedSpinZCurrentBondSourceRetardedSusceptibility system expectation
        velocity spinScale ℏ q K u v t s =
      boundedMeasuredCurrentRetardedSusceptibility system expectation
        (boundedSpinZCurrent velocity spinScale)
        (boundedBondCurrent ℏ q K u v) t s := by
  rfl

end
end Transport
end Fermionic
end SecondQuantization
