import LeanCondensedMatter.SecondQuantization.Fermionic.Lattice.Spinful
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.ConventionalCurrentResponse
import LeanCondensedMatter.QuantumTheory.LinearResponse.ResponseChannel

set_option linter.style.header false

/-!
# Finite spin-current / electric-source cross response

This module gives a concrete generalized-current response on the finite spinful lattice
`Site × Fin 2`. Its measured spin current is the conventional current associated with the diagonal
internal spin operator,

```text
J^(S_z) = dΓ( 1/2 {v, S_z} ),
```

transported to the bounded finite-lattice Hilbert realization. The source is an ordinary electric
bond current, so the response kernel is genuinely mixed:

```text
χᴿ_{J^(S_z), J^charge_{u→v}}.
```

No equality between spin current and charge current is assumed. The velocity is supplied as a
one-particle operator so later finite Rashba/Dirac models can instantiate it with the velocity derived
from their Hamiltonian. Conductivity normalization and source-dependent contact terms remain separate
from this causal cross-response kernel. The conventional-current/proper-current distinction is
motivated by Shi, Zhang, Xiao, and Niu, *Phys. Rev. Lett.* **96**, 076604 (2006),
[doi:10.1103/PhysRevLett.96.076604](https://doi.org/10.1103/PhysRevLett.96.076604); this module
does not identify the conventional operator with their torque-dipole-completed current. The finite
Rashba, disorder-vertex, and inverse-response follow-ups are tracked in
`notes/roadmaps/spin-hall.md`.
-/

namespace SecondQuantization
namespace Fermionic
namespace Transport

open _root_.SecondQuantization.Fermionic.Lattice
open QuantumTheory.LinearResponse

noncomputable section

variable {Site : Type*} [LinearOrder Site] [Fintype Site]

/-- Bounded conventional spin-z current on the finite spinful lattice. -/
noncomputable def boundedSpinZCurrent
    (velocity : LatticeState (SpinfulSite Site) →ₗ[ℂ] LatticeState (SpinfulSite Site))
    (spinScale : ℂ) :
    FiniteLatticeHilbertFock (SpinfulSite Site) →L[ℂ]
      FiniteLatticeHilbertFock (SpinfulSite Site) :=
  boundedConventionalCurrent velocity (spinZOneBody spinScale)

/-- Neutral fixed-observable response channel for a finite spin-z current driven by an electric
bond-current source. The measured spin current and electric source remain distinct data while the
absence of an explicit observable variation is made visible through `ResponseChannel.fixed`. -/
noncomputable def boundedSpinZCurrentBondSourceResponseChannel
    (velocity : LatticeState (SpinfulSite Site) →ₗ[ℂ] LatticeState (SpinfulSite Site))
    (spinScale ℏ q : ℂ)
    (K : LocallyFiniteHopping (SpinfulSite Site))
    (u v : SpinfulSite Site) :
    ResponseChannel (FiniteLatticeHilbertFock (SpinfulSite Site)) :=
  ResponseChannel.fixed
    (boundedSpinZCurrent velocity spinScale)
    (boundedBondCurrent ℏ q K u v)

/-- Retarded response of a concrete finite spin-z current to an electric bond-current source.

The measured observable and source are intentionally distinct. The source carries electric charge
`q`, while the measured current is generated by the internal spin operator `S_z`. -/
noncomputable def boundedSpinZCurrentBondSourceRetardedSusceptibility
    (system : QuantumTheory.LinearResponse.BoundedFreeSystem
      (FiniteLatticeHilbertFock (SpinfulSite Site)))
    (expectation : QuantumTheory.LinearResponse.NormalizedExpectation
      (FiniteLatticeHilbertFock (SpinfulSite Site)))
    (velocity : LatticeState (SpinfulSite Site) →ₗ[ℂ] LatticeState (SpinfulSite Site))
    (spinScale ℏ q : ℂ)
    (K : LocallyFiniteHopping (SpinfulSite Site))
    (u v : SpinfulSite Site) (t s : ℝ) : ℂ :=
  (boundedSpinZCurrentBondSourceResponseChannel velocity spinScale ℏ q K u v).retardedKernel
    system expectation t s

end
end Transport
end Fermionic
end SecondQuantization
