import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.TwoPoint.SlotSplit.SlotSplitConnectivity
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.TwoPoint.Components.ComponentDecomposition

set_option linter.style.header false

/-!
# Vacuum components across a two-point slot split

When the left two-point piece is externally connected, every vacuum component of the reassembled
diagram lies on the quartic right side, and every connected component of that quartic right side is
one of those vacuum components. Reachability and interaction-sector membership identify the
component supports and produce an equivalence of finite component index types.
-/

namespace SecondQuantization
namespace Common

open Combinatorics

variable {ExternalLabel InternalLabel : Type*} {N : ℕ} {S T : Finset (Fin N)}

private noncomputable def QuarticDiagram.componentRepresentative
    (d : QuarticDiagram InternalLabel N S) (C : d.vertexGraph.componentPartitionOn.parts) : ↥S :=
  ⟨Classical.choose (d.vertexGraph.componentPartitionOn.part_surjOn C.2),
    (Classical.choose_spec (d.vertexGraph.componentPartitionOn.part_surjOn C.2)).1⟩

private theorem QuarticDiagram.componentBlockOn_componentRepresentative
    (d : QuarticDiagram InternalLabel N S) (C : d.vertexGraph.componentPartitionOn.parts) :
    d.vertexGraph.componentBlockOn (d.componentRepresentative C) = (C : Finset (Fin N)) := by
  change d.vertexGraph.componentPartitionOn.part
      (Classical.choose (d.vertexGraph.componentPartitionOn.part_surjOn C.2)) = (C : Finset (Fin N))
  exact (Classical.choose_spec (d.vertexGraph.componentPartitionOn.part_surjOn C.2)).2

variable (h : T ⊆ S)
  (ext : TwoPointDiagram ExternalLabel InternalLabel N T)
  (vac : QuarticDiagram InternalLabel N (S \ T))

/-- The graph-sum isomorphism identifies vacuum-side reachability with reachability in the
quartic vacuum graph. -/
private theorem reachable_ofSlotSplitVacuum_iff (x y : ↥(S \ T)) :
    (TwoPointDiagram.ofSlotSplit h ext vac).vertexGraph.Reachable
      (slotSplitVacuumVertex x) (slotSplitVacuumVertex y) ↔
      vac.vertexGraph.Reachable x y := by
  change (TwoPointDiagram.ofSlotSplit h ext vac).vertexGraph.Reachable
      ((TwoPointDiagram.ofSlotSplitVertexGraphIso h ext vac) (Sum.inr x))
      ((TwoPointDiagram.ofSlotSplitVertexGraphIso h ext vac) (Sum.inr y)) ↔ _
  exact (SimpleGraph.Iso.reachable_iff
    (φ := TwoPointDiagram.ofSlotSplitVertexGraphIso h ext vac)
    (u := Sum.inr x) (v := Sum.inr y)).trans
      (SimpleGraph.reachable_sum_inr_iff ext.vertexGraph vac.vertexGraph x y)

/-- The interaction vertices in the ambient component generated by one vacuum-piece vertex are
exactly that vertex's connected component in the quartic vacuum piece. -/
theorem interactionSector_componentBlock_slotSplitVacuumVertex (v : ↥(S \ T)) :
    interactionSector
        ((TwoPointDiagram.ofSlotSplit h ext vac).vertexGraph.componentBlock
          (slotSplitVacuumVertex v)) =
      vac.vertexGraph.componentBlockOn v := by
  ext x
  constructor
  · intro hx
    obtain ⟨hxS, hxBlock⟩ := (mem_interactionSector _ x).1 hx
    have hreach :
        (TwoPointDiagram.ofSlotSplit h ext vac).vertexGraph.Reachable
          (slotSplitVacuumVertex v) (Sum.inr ⟨x, hxS⟩) :=
      (((TwoPointDiagram.ofSlotSplit h ext vac).vertexGraph.mem_componentBlock
        (slotSplitVacuumVertex v) (Sum.inr ⟨x, hxS⟩)).1 hxBlock).symm
    by_cases hxT : x ∈ T
    · have hsum :
          (ext.vertexGraph ⊕g vac.vertexGraph).Reachable
            (Sum.inr v) (Sum.inl (Sum.inr ⟨x, hxT⟩)) :=
        (SimpleGraph.Iso.reachable_iff
          (φ := TwoPointDiagram.ofSlotSplitVertexGraphIso h ext vac)
          (u := Sum.inr v) (v := Sum.inl (Sum.inr ⟨x, hxT⟩))).mp
          (by
            change (TwoPointDiagram.ofSlotSplit h ext vac).vertexGraph.Reachable
              (slotSplitVacuumVertex v) (slotSplitVertex h (Sum.inr ⟨x, hxT⟩))
            simpa [slotSplitVertex] using hreach)
      exact False.elim (SimpleGraph.not_reachable_sum_inl_inr _ _ hsum.symm)
    · let y : ↥(S \ T) := ⟨x, Finset.mem_sdiff.mpr ⟨hxS, hxT⟩⟩
      have hreach' : vac.vertexGraph.Reachable v y :=
        (reachable_ofSlotSplitVacuum_iff h ext vac v y).1 (by
          change (TwoPointDiagram.ofSlotSplit h ext vac).vertexGraph.Reachable
            (slotSplitVacuumVertex v) (Sum.inr ⟨x, hxS⟩)
          exact hreach)
      exact (vac.vertexGraph.mem_componentBlockOn v).2 ⟨y.2, hreach'.symm⟩
  · intro hx
    obtain ⟨hxST, hreach⟩ := (vac.vertexGraph.mem_componentBlockOn v).1 hx
    let y : ↥(S \ T) := ⟨x, hxST⟩
    have hamb :
        (TwoPointDiagram.ofSlotSplit h ext vac).vertexGraph.Reachable
          (slotSplitVacuumVertex y) (slotSplitVacuumVertex v) :=
      (reachable_ofSlotSplitVacuum_iff h ext vac y v).2 hreach
    apply (mem_interactionSector _ x).2
    refine ⟨(Finset.mem_sdiff.mp hxST).1, ?_⟩
    apply ((TwoPointDiagram.ofSlotSplit h ext vac).vertexGraph.mem_componentBlock
      (slotSplitVacuumVertex v) (Sum.inr ⟨x, (Finset.mem_sdiff.mp hxST).1⟩)).2
    simpa [y, slotSplitVacuumVertex] using hamb

/-- A component generated by a vertex of the quartic right side is a vacuum component of the
reassembled two-point diagram. -/
theorem componentBlock_slotSplitVacuumVertex_mem_vacuumComponentParts
    (v : ↥(S \ T)) :
    let d := TwoPointDiagram.ofSlotSplit h ext vac
    let B : d.vertexGraph.componentPartition.parts :=
      ⟨d.vertexGraph.componentBlock (slotSplitVacuumVertex v),
        d.vertexGraph.componentBlock_mem_componentPartition (slotSplitVacuumVertex v)⟩
    B ∈ (vacuumComponentParts d.vertexGraph) := by
  dsimp only
  rw [mem_vacuumComponentParts]
  unfold ComponentIsVacuum ComponentMeetsExternal
  rintro ⟨e, he⟩
  have hreach :
      (TwoPointDiagram.ofSlotSplit h ext vac).vertexGraph.Reachable
        (Sum.inl e) (slotSplitVacuumVertex v) :=
    ((TwoPointDiagram.ofSlotSplit h ext vac).vertexGraph.mem_componentBlock
      (slotSplitVacuumVertex v) (Sum.inl e)).1 he
  have hsum :
      (ext.vertexGraph ⊕g vac.vertexGraph).Reachable
        (Sum.inl (Sum.inl e)) (Sum.inr v) :=
    (SimpleGraph.Iso.reachable_iff
      (φ := TwoPointDiagram.ofSlotSplitVertexGraphIso h ext vac)
      (u := Sum.inl (Sum.inl e)) (v := Sum.inr v)).mp
      (by
        change (TwoPointDiagram.ofSlotSplit h ext vac).vertexGraph.Reachable
          (slotSplitVertex h (Sum.inl e)) (slotSplitVacuumVertex v)
        simpa [slotSplitVertex] using hreach)
  exact SimpleGraph.not_reachable_sum_inl_inr _ _ hsum

/-- Send a quartic vacuum-piece component to the corresponding ambient vacuum component. -/
noncomputable def slotSplitVacuumComponentPart
    (C : vac.vertexGraph.componentPartitionOn.parts) :
    ↥(vacuumComponentParts (TwoPointDiagram.ofSlotSplit h ext vac).vertexGraph) :=
  let v := vac.componentRepresentative C
  let d := TwoPointDiagram.ofSlotSplit h ext vac
  let B : d.vertexGraph.componentPartition.parts :=
    ⟨d.vertexGraph.componentBlock (slotSplitVacuumVertex v),
      d.vertexGraph.componentBlock_mem_componentPartition (slotSplitVacuumVertex v)⟩
  ⟨B, componentBlock_slotSplitVacuumVertex_mem_vacuumComponentParts h ext vac v⟩

/-- The ambient interaction part of the image component is exactly the original quartic component. -/
theorem interactionSector_slotSplitVacuumComponentPart
    (C : vac.vertexGraph.componentPartitionOn.parts) :
    interactionSector
        ((slotSplitVacuumComponentPart h ext vac C).1.1 :
          Finset (TwoPointVertex S)) =
      (C : Finset (Fin N)) := by
  change interactionSector
      ((TwoPointDiagram.ofSlotSplit h ext vac).vertexGraph.componentBlock
        (slotSplitVacuumVertex (vac.componentRepresentative C))) = _
  rw [interactionSector_componentBlock_slotSplitVacuumVertex]
  exact vac.componentBlockOn_componentRepresentative C

/-- The quartic-to-ambient vacuum component map is injective. -/
private theorem slotSplitVacuumComponentPart_injective :
    Function.Injective (slotSplitVacuumComponentPart h ext vac) := by
  intro C D hCD
  apply Subtype.ext
  have hparts := congrArg (fun B => B.1.1) hCD
  have hint := congrArg interactionSector hparts
  rw [interactionSector_slotSplitVacuumComponentPart,
    interactionSector_slotSplitVacuumComponentPart] at hint
  exact hint

/-- If the external piece is externally connected, an interaction vertex in an ambient vacuum
component must lie on the quartic right side. -/
private theorem not_mem_left_of_mem_vacuumComponentPart
    (hext : ext.IsExternallyConnected)
    (B : ↥(vacuumComponentParts (TwoPointDiagram.ofSlotSplit h ext vac).vertexGraph))
    (w : ↥S) (hwB : (Sum.inr w : TwoPointVertex S) ∈ (B.1 : Finset (TwoPointVertex S))) :
    (w : Fin N) ∉ T := by
  intro hwT
  let d := TwoPointDiagram.ofSlotSplit h ext vac
  have hExternal :
      (Sum.inr w : TwoPointVertex S) ∈ d.vertexGraph.componentBlock (Sum.inl 0) := by
    apply (mem_interactionSector_subtype _ w).1
    rw [interactionSector_externalComponent_ofSlotSplit h ext vac hext]
    exact hwT
  have hBlocks : B.1.1 = d.vertexGraph.componentBlock (Sum.inl 0) := by
    calc
      B.1.1 = d.vertexGraph.componentBlock (Sum.inr w) :=
        ((d.vertexGraph.componentBlock_eq_iff_mem B.1.2 _).2 hwB).symm
      _ = _ := (d.vertexGraph.componentBlock_eq_iff_mem
        (d.vertexGraph.componentBlock_mem_componentPartition (Sum.inl 0)) _).2 hExternal
  exact ((mem_vacuumComponentParts d.vertexGraph B.1).1 B.2)
    ⟨0, by rw [hBlocks]; exact d.vertexGraph.self_mem_componentBlock (Sum.inl 0)⟩

/-- With an externally connected left piece, every ambient vacuum component comes from a quartic
right-side component. -/
private theorem slotSplitVacuumComponentPart_surjective
    (hext : ext.IsExternallyConnected) :
    Function.Surjective (slotSplitVacuumComponentPart h ext vac) := by
  intro B
  obtain ⟨x, hxB⟩ :=
    (TwoPointDiagram.ofSlotSplit h ext vac).vertexGraph.componentPartition.nonempty_of_mem_parts B.1.2
  cases x with
  | inl e =>
      have hVac :
          ComponentIsVacuum (B.1 : Finset (TwoPointVertex S)) :=
        (mem_vacuumComponentParts (TwoPointDiagram.ofSlotSplit h ext vac).vertexGraph B.1).1 B.2
      exact False.elim (hVac ⟨e, hxB⟩)
  | inr w =>
      have hwNot : (w : Fin N) ∉ T :=
        not_mem_left_of_mem_vacuumComponentPart h ext vac hext B w hxB
      let v : ↥(S \ T) := ⟨w.1, Finset.mem_sdiff.mpr ⟨w.2, hwNot⟩⟩
      let C : vac.vertexGraph.componentPartitionOn.parts :=
        ⟨vac.vertexGraph.componentBlockOn v, by
          unfold SimpleGraph.componentBlockOn
          exact vac.vertexGraph.componentPartitionOn.part_mem.2 v.2⟩
      refine ⟨C, ?_⟩
      apply Subtype.ext
      apply interactionSector_component_unique
        (TwoPointDiagram.ofSlotSplit h ext vac).vertexGraph w
      · rw [interactionSector_slotSplitVacuumComponentPart]
        change (w : Fin N) ∈ vac.vertexGraph.componentPartitionOn.part (v : Fin N)
        have hwv : (w : Fin N) = (v : Fin N) := rfl
        rw [hwv]
        exact vac.vertexGraph.componentPartitionOn.mem_part v.2
      · exact (mem_interactionSector_subtype
          (B.1 : Finset (TwoPointVertex S)) w).2 hxB

/-- Connected components of the quartic vacuum piece are equivalent to vacuum components of the
reassembled two-point diagram when the external piece is externally connected. -/
noncomputable def slotSplitVacuumComponentEquiv
    (hext : ext.IsExternallyConnected) :
    vac.vertexGraph.componentPartitionOn.parts ≃
      ↥(vacuumComponentParts (TwoPointDiagram.ofSlotSplit h ext vac).vertexGraph) :=
  Equiv.ofBijective (slotSplitVacuumComponentPart h ext vac)
    ⟨slotSplitVacuumComponentPart_injective h ext vac,
      slotSplitVacuumComponentPart_surjective h ext vac hext⟩

@[simp]
theorem slotSplitVacuumComponentEquiv_apply
    (hext : ext.IsExternallyConnected) (C : vac.vertexGraph.componentPartitionOn.parts) :
    slotSplitVacuumComponentEquiv h ext vac hext C =
      slotSplitVacuumComponentPart h ext vac C :=
  rfl

end Common
end SecondQuantization
