import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.TwoPoint.SlotSplit.SlotSplitConnectivity
import LeanCondensedMatter.Combinatorics.SimpleGraphComponentPartition

set_option linter.style.header false

/-!
# Vacuum connectivity across the two-point slot split

For a reconstructed slot-split diagram, adjacency and reachability among vertices of the quartic
vacuum sector agree exactly with adjacency and reachability in the quartic piece itself.

Thus connected components on the quartic side can be identified with the vacuum components of the
ambient two-point diagram. The statement is purely graph-theoretic and independent of particle
statistics or amplitudes.
-/

namespace SecondQuantization
namespace Common

open Combinatorics

variable {ExternalLabel InternalLabel : Type*} {N : ℕ} {S T : Finset (Fin N)}

variable (h : T ⊆ S)
  (ext : TwoPointDiagram ExternalLabel InternalLabel N T)
  (vac : QuarticDiagram InternalLabel N (S \ T))

/-- The graph-sum isomorphism identifies vacuum-side reachability with reachability in the
quartic vacuum graph. -/
private theorem reachable_ofSlotSplitVacuum_iff (x y : ↥(S \ T)) :
    (TwoPointDiagram.ofSlotSplit h ext vac).vertexGraph.Reachable
      (slotSplitVacuumVertex x) (slotSplitVacuumVertex y) ↔
      vac.vertexGraph.Reachable x y := by
  change (TwoPointDiagram.ofSlotSplit h ext vac).vertexGraph.Reachable
      ((TwoPointDiagram.ofSlotSplitVertexGraphIso h ext vac) (Sum.inr x))
      ((TwoPointDiagram.ofSlotSplitVertexGraphIso h ext vac) (Sum.inr y)) ↔ _
  exact (SimpleGraph.Iso.reachable_iff
    (φ := TwoPointDiagram.ofSlotSplitVertexGraphIso h ext vac)
    (u := Sum.inr x) (v := Sum.inr y)).trans
      (SimpleGraph.reachable_sum_inr_iff ext.vertexGraph vac.vertexGraph x y)

/-- The interaction vertices in the ambient component generated by one vacuum-piece vertex are
exactly that vertex's connected component in the quartic vacuum piece. -/
theorem interactionSector_componentBlock_slotSplitVacuumVertex (v : ↥(S \ T)) :
    interactionSector
        ((TwoPointDiagram.ofSlotSplit h ext vac).vertexGraph.componentBlock
          (slotSplitVacuumVertex v)) =
      vac.vertexGraph.componentBlockOn v := by
  ext x
  constructor
  · intro hx
    obtain ⟨hxS, hxBlock⟩ := (mem_interactionSector _ x).1 hx
    have hreach :
        (TwoPointDiagram.ofSlotSplit h ext vac).vertexGraph.Reachable
          (slotSplitVacuumVertex v) (Sum.inr ⟨x, hxS⟩) :=
      (((TwoPointDiagram.ofSlotSplit h ext vac).vertexGraph.mem_componentBlock
        (slotSplitVacuumVertex v) (Sum.inr ⟨x, hxS⟩)).1 hxBlock).symm
    by_cases hxT : x ∈ T
    · have hsum :
          (ext.vertexGraph ⊕g vac.vertexGraph).Reachable
            (Sum.inr v) (Sum.inl (Sum.inr ⟨x, hxT⟩)) :=
        (SimpleGraph.Iso.reachable_iff
          (φ := TwoPointDiagram.ofSlotSplitVertexGraphIso h ext vac)
          (u := Sum.inr v) (v := Sum.inl (Sum.inr ⟨x, hxT⟩))).mp
          (by
            change (TwoPointDiagram.ofSlotSplit h ext vac).vertexGraph.Reachable
              (slotSplitVacuumVertex v) (slotSplitVertex h (Sum.inr ⟨x, hxT⟩))
            simpa [slotSplitVertex] using hreach)
      exact False.elim (SimpleGraph.not_reachable_sum_inl_inr _ _ hsum.symm)
    · let y : ↥(S \ T) := ⟨x, Finset.mem_sdiff.mpr ⟨hxS, hxT⟩⟩
      have hreach' : vac.vertexGraph.Reachable v y :=
        (reachable_ofSlotSplitVacuum_iff h ext vac v y).1 (by
          change (TwoPointDiagram.ofSlotSplit h ext vac).vertexGraph.Reachable
            (slotSplitVacuumVertex v) (Sum.inr ⟨x, hxS⟩)
          exact hreach)
      exact (vac.vertexGraph.mem_componentBlockOn v).2 ⟨y.2, hreach'.symm⟩
  · intro hx
    obtain ⟨hxST, hreach⟩ := (vac.vertexGraph.mem_componentBlockOn v).1 hx
    let y : ↥(S \ T) := ⟨x, hxST⟩
    have hamb :
        (TwoPointDiagram.ofSlotSplit h ext vac).vertexGraph.Reachable
          (slotSplitVacuumVertex y) (slotSplitVacuumVertex v) :=
      (reachable_ofSlotSplitVacuum_iff h ext vac y v).2 hreach
    apply (mem_interactionSector _ x).2
    refine ⟨(Finset.mem_sdiff.mp hxST).1, ?_⟩
    apply ((TwoPointDiagram.ofSlotSplit h ext vac).vertexGraph.mem_componentBlock
      (slotSplitVacuumVertex v) (Sum.inr ⟨x, (Finset.mem_sdiff.mp hxST).1⟩)).2
    simpa [y, slotSplitVacuumVertex] using hamb

end Common
end SecondQuantization
