import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.Evolution.Stone1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.Evolution.RepresentativeContinuity1D

set_option linter.style.header false

/-!
# Continuum time evolution

One-dimensional continuum time evolution generated by self-adjoint Hamiltonians, together with
continuity properties of representative wavefunctions.
-/
