import LeanCondensedMatter.Analysis.Dyson.Uniqueness
import Mathlib.Analysis.SpecialFunctions.Exponential

set_option linter.style.header false

/-!
# Constant-generator Dyson evolution

For a time-independent bounded interaction, the generic Dyson evolution is the Banach-algebra
exponential generated by the constant interaction. The proof uses the generic Volterra uniqueness
theorem rather than recomputing the coefficient series.
-/

namespace Dyson

open Set

noncomputable section

variable {A : Type*} [NormedRing A] [NormedAlgebra ℂ A] [CompleteSpace A]

/-- The Banach-algebra exponential candidate for a constant interaction. -/
noncomputable def constantExponential (K : A) (lam : ℂ) (τ : ℝ) : A :=
  NormedSpace.exp (-(((τ : ℝ) • lam) • K))

/-- The constant exponential candidate solves the expected interaction-picture differential
equation. -/
theorem hasDerivAt_constantExponential (K : A) (lam : ℂ) (τ : ℝ) :
    HasDerivAt (constantExponential K lam)
      (-(lam • (K * constantExponential K lam τ))) τ := by
  change HasDerivAt
    (fun u : ℝ => NormedSpace.exp (-(((u : ℝ) • lam) • K)))
    (-(lam • (K * NormedSpace.exp (-(((τ : ℝ) • lam) • K))))) τ
  simpa only [smul_neg, smul_assoc, neg_mul, smul_mul_assoc] using
    (hasDerivAt_exp_smul_const' (-(lam • K)) τ)

/-- The constant exponential candidate is continuous in time. -/
theorem continuous_constantExponential (K : A) (lam : ℂ) :
    Continuous (constantExponential K lam) := by
  rw [continuous_iff_continuousAt]
  intro τ
  exact (hasDerivAt_constantExponential K lam τ).continuousAt

/-- The constant exponential candidate satisfies the constant-generator Volterra equation. -/
theorem constantExponential_eq_one_sub_integral (K : A) (lam : ℂ) (τ : ℝ) :
    constantExponential K lam τ =
      1 - lam • ∫ σ in (0 : ℝ)..τ, K * constantExponential K lam σ := by
  let U : ℝ → A := constantExponential K lam
  let f : ℝ → A := fun σ => -(lam • (K * U σ))
  have hderiv : ∀ σ ∈ uIcc (0 : ℝ) τ, HasDerivAt U (f σ) σ := by
    intro σ _
    exact hasDerivAt_constantExponential K lam σ
  have hf : Continuous f := by
    exact (continuous_const.smul
      (continuous_const.mul (continuous_constantExponential K lam))).neg
  have hFTC : (∫ σ in (0 : ℝ)..τ, f σ) = U τ - U 0 :=
    intervalIntegral.integral_eq_sub_of_hasDerivAt hderiv (hf.intervalIntegrable 0 τ)
  have hzero : U 0 = 1 := by
    simp [U, constantExponential]
  rw [hzero] at hFTC
  have hFTC' :
      -(lam • ∫ σ in (0 : ℝ)..τ, K * U σ) = U τ - 1 := by
    simpa only [f, intervalIntegral.integral_neg, intervalIntegral.integral_smul] using hFTC
  change U τ = 1 - lam • ∫ σ in (0 : ℝ)..τ, K * U σ
  calc
    U τ = 1 + (U τ - 1) := by abel
    _ = 1 + (-(lam • ∫ σ in (0 : ℝ)..τ, K * U σ)) := by rw [← hFTC']
    _ = 1 - lam • ∫ σ in (0 : ℝ)..τ, K * U σ := by abel

/-- On nonnegative time, the Dyson evolution for a constant interaction is the corresponding
Banach-algebra exponential. -/
theorem evolution_const_eq_exp_of_nonneg (K : A) (lam : ℂ) {τ : ℝ}
    (hτ : 0 ≤ τ) (hOne : ‖(1 : A)‖ ≤ 1) :
    evolution (fun _ : ℝ => K) lam τ =
      NormedSpace.exp (-(((τ : ℝ) • lam) • K)) := by
  have hEq := eqOn_evolution_of_volterra_of_bound
    (V := fun _ : ℝ => K) (U := constantExponential K lam)
    (β := τ) (M := ‖K‖)
    continuous_const hτ hOne (norm_nonneg K)
    (fun _ _ => le_rfl) lam
    (continuous_constantExponential K lam).continuousOn
    (fun t _ => by
      simpa only using constantExponential_eq_one_sub_integral K lam t)
  simpa only [constantExponential] using (hEq ⟨hτ, le_rfl⟩).symm

end
end Dyson
