import LeanCondensedMatter.Analysis.Operator.Unbounded.BoundedUnitaryEvolution
import Mathlib.Tactic

set_option linter.style.header false

/-!
# Algebra of bounded unitary evolutions

For commuting bounded generators, the corresponding exponential evolutions factor through the sum
of the generators.  This is the algebraic factorization used to compare the bounded Stone
approximants at two regularization scales.
-/

namespace LinearPMap

noncomputable section

open Complex
open scoped InnerProductSpace

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-- Evolutions generated by commuting bounded operators factor through the sum of generators. -/
theorem boundedUnitaryEvolution_add_generator_of_commute
    (B C : H →L[ℂ] H) (hBC : Commute B C) (t : ℝ) :
    boundedUnitaryEvolution (B + C) t =
      boundedUnitaryEvolution B t * boundedUnitaryEvolution C t := by
  unfold boundedUnitaryEvolution
  rw [smul_add]
  apply NormedSpace.exp_add_of_commute_of_mem_ball (𝕂 := ℂ)
  · exact (hBC.smul_left _).smul_right _
  · rw [NormedSpace.expSeries_radius_eq_top]
    exact edist_lt_top _ _
  · rw [NormedSpace.expSeries_radius_eq_top]
    exact edist_lt_top _ _

end

end LinearPMap
