import LeanCondensedMatter.Analysis.Operator.Unbounded.ResolventConvergence
import Mathlib.Analysis.Normed.Algebra.Exponential
import Mathlib.Analysis.SpecialFunctions.Exponential
import Mathlib.Analysis.Complex.RealDeriv
import Mathlib.Tactic

set_option linter.style.header false

/-!
# Unitary evolution of bounded self-adjoint operators

For a bounded self-adjoint operator `B` on a complex Hilbert space, the Banach-algebra exponential

`U_B(t) = exp (-i t B)`

defines a norm-continuous one-parameter unitary group. For commuting bounded generators, evolution
under their sum factors into the product of the individual evolutions. Applying this construction to
the bounded resolvent approximants from `ResolventApproximation` gives the approximating unitary
groups used in the Stone-theorem construction.
-/

namespace LinearPMap

noncomputable section

open Complex
open scoped InnerProductSpace

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

private noncomputable def unitaryTimeCoefficient (t : ℝ) : ℂ :=
  -((t : ℂ) * I)

@[simp]
private theorem unitaryTimeCoefficient_zero : unitaryTimeCoefficient 0 = 0 := by
  simp [unitaryTimeCoefficient]

private theorem unitaryTimeCoefficient_add (t s : ℝ) :
    unitaryTimeCoefficient (t + s) = unitaryTimeCoefficient t + unitaryTimeCoefficient s := by
  simp [unitaryTimeCoefficient]
  ring

@[simp]
private theorem star_unitaryTimeCoefficient (t : ℝ) :
    star (unitaryTimeCoefficient t) = unitaryTimeCoefficient (-t) := by
  simp [unitaryTimeCoefficient]

/-- The bounded Schrödinger evolution generated by a bounded operator `B`. -/
noncomputable def boundedUnitaryEvolution (B : H →L[ℂ] H) (t : ℝ) : H →L[ℂ] H :=
  NormedSpace.exp (unitaryTimeCoefficient t • B)

omit [CompleteSpace H] in
@[simp]
theorem boundedUnitaryEvolution_zero (B : H →L[ℂ] H) :
    boundedUnitaryEvolution B 0 = 1 := by
  simp [boundedUnitaryEvolution]

omit [CompleteSpace H] in
private theorem exp_argument_mem_ball (B : H →L[ℂ] H) (t : ℝ) :
    unitaryTimeCoefficient t • B ∈
      Metric.eball 0 (NormedSpace.expSeries ℂ (H →L[ℂ] H)).radius := by
  rw [NormedSpace.expSeries_radius_eq_top]
  exact edist_lt_top _ _

/-- Exponentials of scalar multiples of one bounded operator form a one-parameter group. -/
theorem boundedUnitaryEvolution_add (B : H →L[ℂ] H) (t s : ℝ) :
    boundedUnitaryEvolution B (t + s) =
      boundedUnitaryEvolution B t * boundedUnitaryEvolution B s := by
  change NormedSpace.exp (unitaryTimeCoefficient (t + s) • B) =
    NormedSpace.exp (unitaryTimeCoefficient t • B) *
      NormedSpace.exp (unitaryTimeCoefficient s • B)
  rw [unitaryTimeCoefficient_add, add_smul]
  exact NormedSpace.exp_add_of_commute_of_mem_ball (𝕂 := ℂ)
    (((Commute.refl B).smul_left (unitaryTimeCoefficient t)).smul_right
      (unitaryTimeCoefficient s))
    (exp_argument_mem_ball B t) (exp_argument_mem_ball B s)

/-- Evolutions generated by commuting bounded operators factor through the sum of generators. -/
theorem boundedUnitaryEvolution_add_generator_of_commute
    (B C : H →L[ℂ] H) (hBC : Commute B C) (t : ℝ) :
    boundedUnitaryEvolution (B + C) t =
      boundedUnitaryEvolution B t * boundedUnitaryEvolution C t := by
  unfold boundedUnitaryEvolution
  rw [smul_add]
  apply NormedSpace.exp_add_of_commute_of_mem_ball (𝕂 := ℂ)
  · exact (hBC.smul_left _).smul_right _
  · rw [NormedSpace.expSeries_radius_eq_top]
    exact edist_lt_top _ _
  · rw [NormedSpace.expSeries_radius_eq_top]
    exact edist_lt_top _ _

/-- For self-adjoint `B`, the adjoint evolution is evolution at negative time. -/
theorem boundedUnitaryEvolution_star
    (B : H →L[ℂ] H) (hB : IsSelfAdjoint B) (t : ℝ) :
    star (boundedUnitaryEvolution B t) = boundedUnitaryEvolution B (-t) := by
  have hBstar : star B = B := by
    simpa only [isSelfAdjoint_iff] using hB
  simp [boundedUnitaryEvolution, NormedSpace.star_exp, hBstar]

/-- A bounded self-adjoint exponential has its adjoint as a left inverse. -/
theorem boundedUnitaryEvolution_star_mul
    (B : H →L[ℂ] H) (hB : IsSelfAdjoint B) (t : ℝ) :
    star (boundedUnitaryEvolution B t) * boundedUnitaryEvolution B t = 1 := by
  rw [boundedUnitaryEvolution_star B hB t]
  rw [← boundedUnitaryEvolution_add]
  simp

/-- A bounded self-adjoint exponential has its adjoint as a right inverse. -/
theorem boundedUnitaryEvolution_mul_star
    (B : H →L[ℂ] H) (hB : IsSelfAdjoint B) (t : ℝ) :
    boundedUnitaryEvolution B t * star (boundedUnitaryEvolution B t) = 1 := by
  rw [boundedUnitaryEvolution_star B hB t]
  rw [← boundedUnitaryEvolution_add]
  simp

/-- The bounded exponential group is continuous in operator norm, hence in particular strongly
continuous on every vector. -/
theorem boundedUnitaryEvolution_continuous (B : H →L[ℂ] H) :
    Continuous (boundedUnitaryEvolution B) := by
  have hexp : Continuous
      (NormedSpace.exp : (H →L[ℂ] H) → (H →L[ℂ] H)) := by
    rw [← continuousOn_univ, ← Metric.eball_top_eq_univ (0 : H →L[ℂ] H),
      ← NormedSpace.expSeries_radius_eq_top ℂ (H →L[ℂ] H)]
    exact NormedSpace.continuousOn_exp (𝕂 := ℂ)
  unfold boundedUnitaryEvolution unitaryTimeCoefficient
  exact hexp.comp (by fun_prop)

/-- The operator-norm derivative of the bounded unitary evolution. -/
theorem boundedUnitaryEvolution_hasDerivAt (B : H →L[ℂ] H) (t : ℝ) :
    HasDerivAt (fun τ : ℝ => boundedUnitaryEvolution B τ)
      (boundedUnitaryEvolution B t * ((-I : ℂ) • B)) t := by
  have hc :=
    hasDerivAt_exp_smul_const ((-I : ℂ) • B) (t : ℂ)
  have hr := (hc.hasFDerivAt.restrictScalars ℝ).comp t Complex.ofRealCLM.hasFDerivAt
  have hd := hr.hasDerivAt
  simpa [Function.comp_def, boundedUnitaryEvolution, unitaryTimeCoefficient, smul_smul] using hd

/-- The unitary group obtained by exponentiating the bounded resolvent approximation `Aᵣ`. -/
noncomputable def resolventApproximationEvolution
    (A : H →ₗ.[ℂ] H) (hA : IsSelfAdjoint A) (r : ℝ) (hr : 0 < r) (t : ℝ) : H →L[ℂ] H :=
  boundedUnitaryEvolution (boundedSelfAdjointApproximation A hA r hr) t

@[simp]
theorem resolventApproximationEvolution_zero
    (A : H →ₗ.[ℂ] H) (hA : IsSelfAdjoint A) (r : ℝ) (hr : 0 < r) :
    resolventApproximationEvolution A hA r hr 0 = 1 := by
  exact boundedUnitaryEvolution_zero _

/-- Each bounded resolvent approximation gives a one-parameter group. -/
theorem resolventApproximationEvolution_add
    (A : H →ₗ.[ℂ] H) (hA : IsSelfAdjoint A) (r : ℝ) (hr : 0 < r) (t s : ℝ) :
    resolventApproximationEvolution A hA r hr (t + s) =
      resolventApproximationEvolution A hA r hr t *
        resolventApproximationEvolution A hA r hr s := by
  exact boundedUnitaryEvolution_add _ t s

/-- The adjoint of an approximating evolution reverses time. -/
theorem resolventApproximationEvolution_star
    (A : H →ₗ.[ℂ] H) (hA : IsSelfAdjoint A) (r : ℝ) (hr : 0 < r) (t : ℝ) :
    star (resolventApproximationEvolution A hA r hr t) =
      resolventApproximationEvolution A hA r hr (-t) := by
  exact boundedUnitaryEvolution_star _
    (boundedSelfAdjointApproximation_isSelfAdjoint A hA r hr) t

/-- The approximating evolution is unitary, left-inverse form. -/
theorem resolventApproximationEvolution_star_mul
    (A : H →ₗ.[ℂ] H) (hA : IsSelfAdjoint A) (r : ℝ) (hr : 0 < r) (t : ℝ) :
    star (resolventApproximationEvolution A hA r hr t) *
        resolventApproximationEvolution A hA r hr t = 1 := by
  exact boundedUnitaryEvolution_star_mul _
    (boundedSelfAdjointApproximation_isSelfAdjoint A hA r hr) t

/-- The approximating evolution is unitary, right-inverse form. -/
theorem resolventApproximationEvolution_mul_star
    (A : H →ₗ.[ℂ] H) (hA : IsSelfAdjoint A) (r : ℝ) (hr : 0 < r) (t : ℝ) :
    resolventApproximationEvolution A hA r hr t *
        star (resolventApproximationEvolution A hA r hr t) = 1 := by
  exact boundedUnitaryEvolution_mul_star _
    (boundedSelfAdjointApproximation_isSelfAdjoint A hA r hr) t

/-- Each approximating unitary group is continuous in operator norm. -/
theorem resolventApproximationEvolution_continuous
    (A : H →ₗ.[ℂ] H) (hA : IsSelfAdjoint A) (r : ℝ) (hr : 0 < r) :
    Continuous (resolventApproximationEvolution A hA r hr) := by
  exact boundedUnitaryEvolution_continuous _

/-- The bounded approximating evolution satisfies its bounded-generator differential equation in
operator norm. -/
theorem resolventApproximationEvolution_hasDerivAt
    (A : H →ₗ.[ℂ] H) (hA : IsSelfAdjoint A) (r : ℝ) (hr : 0 < r) (t : ℝ) :
    HasDerivAt (fun τ : ℝ => resolventApproximationEvolution A hA r hr τ)
      (resolventApproximationEvolution A hA r hr t *
        ((-I : ℂ) • boundedSelfAdjointApproximation A hA r hr)) t := by
  exact boundedUnitaryEvolution_hasDerivAt _ t

end

end LinearPMap
