import LeanCondensedMatter.Analysis.Operator.Unbounded.ResolventEvolutionGenerator

set_option linter.style.header false

/-!
# Stone evolution

Domain-aware Stone evolution generated by a self-adjoint `LinearPMap`.

The construction yields a bounded one-parameter evolution with its zero-time law, additive group law,
adjoint/time-reversal law, norm preservation, preservation of the generator domain, and strong
generator equation. Resolvent approximations and their convergence provide the analytic construction
of this evolution.
-/
