import LeanCondensedMatter.Analysis.Operator.Unbounded.ResolventEvolutionGenerator

set_option linter.style.header false

/-!
# Stone evolution

Public routing module for the domain-aware Stone evolution generated by a self-adjoint
`LinearPMap`.  The route exposes the limiting bounded evolution together with its zero-time law,
additive group law, adjoint/time-reversal law, norm preservation, preservation of the original
operator domain, and strong generator equation.

The resolvent approximation, convergence estimates, strong-limit construction, and resolvent
transport proofs remain implementation-stage modules.  Consumers should import this route rather
than depending on that proof-stage import chain directly.
-/
