import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.BoundedOneBodyResponse
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.BoundedCurrentResponse
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.IntrinsicFluxResponse
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.ConventionalCurrentResponse
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.SpinCurrentResponse
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.ConductivityNormalization
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.FiniteConductivityTable
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.FiniteEvaluation
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.FrequencyResponse
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.GeometricCurrentResponse
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.HarmonicSourceResponse
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.HermitianBondCurrentResponse
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.InfiniteTimeFrequencyResponse
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.KuboBastinSpectral
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.KuboBastinTrace
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.KuboGreenwood
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.PeierlsContactResponse
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.SpectralFrequencyResponse
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.StaticKuboBastinResponse
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.StationaryFrequencyResponse
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.StredaOccupation
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.StredaCommonKernel
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.StaticStredaWardBridge
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.FiniteDisorderConductivity

set_option linter.style.header false

/-!
# Fermionic transport adapters

Canonical downstream owner for fermionic Kubo/frequency response, intrinsic-flux and generalized
current response, conductivity normalization, Kubo–Greenwood/Bastin/Středa, Ward, finite-table
evaluation, and finite-disorder adapters. Generic reusable response, occupation, resolvent, trace,
and Středa integration theory remains under `QuantumTheory`.

This layer consumes `Fermionic.Lattice` model operators and does not own finite toy checks; those are
terminal consumers under `Fermionic.Validation`. Old transport declarations are not forwarded from
`Fermionic.Field`.
-/
