import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.BoundedOneBodyResponse
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.IntrinsicFluxResponse
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.ConventionalCurrentResponse
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.CorrectedCurrentResponse
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.SpinCurrentResponse
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.ConductivityNormalization
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.FiniteConductivityTable
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.FrequencyResponse
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.GeometricCurrentResponse
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.HarmonicSourceResponse
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.InfiniteTimeFrequencyResponse
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.KuboBastinSpectral
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.KuboBastinTrace
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.CorrectedCurrentKuboBastin
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.GeneralizedStaticStreda
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.CorrectedCurrentStreda
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.KuboGreenwood
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.SpectralFrequencyResponse
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.StaticKuboBastinResponse
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.StationaryFrequencyResponse
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.StredaOccupation
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.StredaCommonKernel
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.StaticStredaWardBridge
import LeanCondensedMatter.SecondQuantization.Fermionic.Transport.FiniteDisorderConductivity

set_option linter.style.header false

/-!
# Fermionic transport adapters

Canonical downstream owner for fermionic Kubo/frequency response, intrinsic-flux and generalized
current response, conductivity normalization, directional Kubo–Greenwood/Bastin/Středa, Ward,
finite-table evaluation, and finite-disorder adapters. Generic reusable response and density theory
remains under `QuantumTheory`, while statistics-independent Kubo–Bastin, resolvent, trace, and
Středa infrastructure lives under `QuantumTheory.Transport`.

This layer consumes `Fermionic.Lattice` model operators and does not own finite toy checks; those are
terminal consumers under `Fermionic.Validation`. Old transport declarations are not forwarded from
`Fermionic.Field`.
-/
