import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.TwoPoint.SlotSplitVacuumConnectivity
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.TwoPoint.ComponentDecomposition

set_option linter.style.header false

/-!
# Vacuum components across a two-point slot split

When the left two-point piece is externally connected, every vacuum component of the reassembled
diagram lies on the quartic right side, and every connected component of that quartic right side is
one of those vacuum components.  `SlotSplitVacuumConnectivity` already proves the required
reachability equivalence; this module packages it as an equivalence of component index types.
-/

namespace SecondQuantization
namespace Common

variable {ExternalLabel InternalLabel : Type*} {N : ℕ} {S T : Finset (Fin N)}

private noncomputable def QuarticDiagram.componentRepresentative
    (d : QuarticDiagram InternalLabel N S) (C : d.componentPartition.parts) : ↥S :=
  ⟨Classical.choose (d.componentPartition.part_surjOn C.2),
    (Classical.choose_spec (d.componentPartition.part_surjOn C.2)).1⟩

private theorem QuarticDiagram.componentBlock_componentRepresentative
    (d : QuarticDiagram InternalLabel N S) (C : d.componentPartition.parts) :
    d.componentBlock (d.componentRepresentative C) = (C : Finset (Fin N)) := by
  change d.componentPartition.part
      (Classical.choose (d.componentPartition.part_surjOn C.2)) = (C : Finset (Fin N))
  exact (Classical.choose_spec (d.componentPartition.part_surjOn C.2)).2

variable (h : T ⊆ S)
  (ext : TwoPointDiagram ExternalLabel InternalLabel N T)
  (vac : QuarticDiagram InternalLabel N (S \ T))

/-- A component generated by a vertex of the quartic right side is a vacuum component of the
reassembled two-point diagram. -/
theorem componentBlock_slotSplitVacuumVertex_mem_vacuumComponentParts
    (v : ↥(S \ T)) :
    let d := TwoPointDiagram.ofSlotSplit h ext vac
    let B : d.componentPartition.parts :=
      ⟨d.componentBlock (slotSplitVacuumVertex v),
        d.componentBlock_mem_componentPartition (slotSplitVacuumVertex v)⟩
    B ∈ d.vacuumComponentParts := by
  dsimp only
  rw [TwoPointDiagram.mem_vacuumComponentParts]
  unfold TwoPointDiagram.ComponentIsVacuum TwoPointDiagram.ComponentMeetsExternal
  rintro ⟨e, he⟩
  have hreach :
      (TwoPointDiagram.ofSlotSplit h ext vac).vertexGraph.Reachable
        (Sum.inl e) (slotSplitVacuumVertex v) :=
    ((TwoPointDiagram.ofSlotSplit h ext vac).mem_componentBlock
      (slotSplitVacuumVertex v) (Sum.inl e)).1 he
  obtain ⟨p⟩ := hreach.symm
  obtain ⟨w, hw, -⟩ :=
    exists_reachable_of_walk_ofSlotSplitVacuum h ext vac p v rfl
  simpa [slotSplitVacuumVertex] using hw

/-- Send a quartic vacuum-piece component to the corresponding ambient vacuum component. -/
noncomputable def slotSplitVacuumComponentPart
    (C : vac.componentPartition.parts) :
    ↥(TwoPointDiagram.ofSlotSplit h ext vac).vacuumComponentParts :=
  let v := vac.componentRepresentative C
  let d := TwoPointDiagram.ofSlotSplit h ext vac
  let B : d.componentPartition.parts :=
    ⟨d.componentBlock (slotSplitVacuumVertex v),
      d.componentBlock_mem_componentPartition (slotSplitVacuumVertex v)⟩
  ⟨B, componentBlock_slotSplitVacuumVertex_mem_vacuumComponentParts h ext vac v⟩

/-- The ambient interaction part of the image component is exactly the original quartic component. -/
theorem interactionPart_slotSplitVacuumComponentPart
    (C : vac.componentPartition.parts) :
    TwoPointDiagram.interactionPart
        ((slotSplitVacuumComponentPart h ext vac C).1.1 :
          Finset (TwoPointVertex S)) =
      (C : Finset (Fin N)) := by
  change TwoPointDiagram.interactionPart
      ((TwoPointDiagram.ofSlotSplit h ext vac).componentBlock
        (slotSplitVacuumVertex (vac.componentRepresentative C))) = _
  rw [interactionPart_componentBlock_slotSplitVacuumVertex]
  exact vac.componentBlock_componentRepresentative C

/-- The quartic-to-ambient vacuum component map is injective. -/
theorem slotSplitVacuumComponentPart_injective :
    Function.Injective (slotSplitVacuumComponentPart h ext vac) := by
  intro C D hCD
  apply Subtype.ext
  have hparts := congrArg (fun B => B.1.1) hCD
  have hint := congrArg TwoPointDiagram.interactionPart hparts
  rw [interactionPart_slotSplitVacuumComponentPart,
    interactionPart_slotSplitVacuumComponentPart] at hint
  exact hint

/-- If the external piece is externally connected, an interaction vertex in an ambient vacuum
component must lie on the quartic right side. -/
theorem not_mem_left_of_mem_vacuumComponentPart
    (hext : ext.IsExternallyConnected)
    (B : ↥(TwoPointDiagram.ofSlotSplit h ext vac).vacuumComponentParts)
    (w : ↥S) (hwB : (Sum.inr w : TwoPointVertex S) ∈ (B.1 : Finset (TwoPointVertex S))) :
    (w : Fin N) ∉ T := by
  intro hwT
  obtain ⟨e, he⟩ := hext.1 ⟨w.1, hwT⟩
  have hamb :
      (TwoPointDiagram.ofSlotSplit h ext vac).vertexGraph.Reachable
        (Sum.inl e) (Sum.inr w) := by
    simpa [slotSplitVertex] using
      reachable_ofSlotSplit_of_reachable h ext vac he
  have hblock :
      (TwoPointDiagram.ofSlotSplit h ext vac).componentBlock (Sum.inr w) = B.1.1 :=
    ((TwoPointDiagram.ofSlotSplit h ext vac).componentBlock_eq_iff_mem B.1.2
      (Sum.inr w)).2 hwB
  have heB : (Sum.inl e : TwoPointVertex S) ∈ (B.1 : Finset (TwoPointVertex S)) := by
    rw [← hblock]
    exact ((TwoPointDiagram.ofSlotSplit h ext vac).mem_componentBlock
      (Sum.inr w) (Sum.inl e)).2 hamb
  have hVac :
      (TwoPointDiagram.ofSlotSplit h ext vac).ComponentIsVacuum B.1 :=
    ((TwoPointDiagram.ofSlotSplit h ext vac).mem_vacuumComponentParts B.1).1 B.2
  exact hVac ⟨e, heB⟩

/-- With an externally connected left piece, every ambient vacuum component comes from a quartic
right-side component. -/
theorem slotSplitVacuumComponentPart_surjective
    (hext : ext.IsExternallyConnected) :
    Function.Surjective (slotSplitVacuumComponentPart h ext vac) := by
  intro B
  obtain ⟨x, hxB⟩ :=
    (TwoPointDiagram.ofSlotSplit h ext vac).componentPartition.nonempty_of_mem_parts B.1.2
  cases x with
  | inl e =>
      have hVac :
          (TwoPointDiagram.ofSlotSplit h ext vac).ComponentIsVacuum B.1 :=
        ((TwoPointDiagram.ofSlotSplit h ext vac).mem_vacuumComponentParts B.1).1 B.2
      exact False.elim (hVac ⟨e, hxB⟩)
  | inr w =>
      have hwNot : (w : Fin N) ∉ T :=
        not_mem_left_of_mem_vacuumComponentPart h ext vac hext B w hxB
      let v : ↥(S \ T) := ⟨w.1, Finset.mem_sdiff.mpr ⟨w.2, hwNot⟩⟩
      let C : vac.componentPartition.parts :=
        ⟨vac.componentBlock v, vac.componentBlock_mem_componentPartition v⟩
      refine ⟨C, ?_⟩
      apply Subtype.ext
      apply TwoPointDiagram.interactionPart_component_unique
        (d := TwoPointDiagram.ofSlotSplit h ext vac) w
      · rw [interactionPart_slotSplitVacuumComponentPart]
        exact vac.self_mem_componentBlock v
      · exact (TwoPointDiagram.mem_interactionPart_subtype
          (B.1 : Finset (TwoPointVertex S)) w).2 hxB

/-- Connected components of the quartic vacuum piece are equivalent to vacuum components of the
reassembled two-point diagram when the external piece is externally connected. -/
noncomputable def slotSplitVacuumComponentEquiv
    (hext : ext.IsExternallyConnected) :
    vac.componentPartition.parts ≃
      ↥(TwoPointDiagram.ofSlotSplit h ext vac).vacuumComponentParts :=
  Equiv.ofBijective (slotSplitVacuumComponentPart h ext vac)
    ⟨slotSplitVacuumComponentPart_injective h ext vac,
      slotSplitVacuumComponentPart_surjective h ext vac hext⟩

@[simp]
theorem slotSplitVacuumComponentEquiv_apply
    (hext : ext.IsExternallyConnected) (C : vac.componentPartition.parts) :
    slotSplitVacuumComponentEquiv h ext vac hext C =
      slotSplitVacuumComponentPart h ext vac C :=
  rfl

end Common
end SecondQuantization