import LeanCondensedMatter.Analysis.Calculus.CurrentEquivalence
import LeanCondensedMatter.QuantumMechanics.SingleParticle.IntrinsicLocalizedTransport
import LeanCondensedMatter.QuantumMechanics.SingleParticle.SymmetrizedVelocityCurrent

set_option linter.style.header false

/-!
# Corrected symmetrized-velocity current

For a general transported one-body quantity `m`, the intrinsic localized transport need not be
represented by the symmetrized velocity current `1/2 {v,m}` alone.  The exact algebraic difference
is the double-commutator localization correction.

This module packages that correction as a current functional on one-form-like test data and proves
that

```text
intrinsic transport = conventional/symmetrized current flux + localization correction
```

whenever the Heisenberg evolution of the localizer is represented by a distinguished velocity.
Any other full current functional representing the same transport is equivalent to this corrected
one on exact differentials; it may differ only by extension data invisible to the balance law.
-/

namespace QuantumMechanics
namespace SingleParticle

variable {Test OneForm : Type*}
variable [AddCommGroup Test] [Module ℂ Test]
variable [AddCommGroup OneForm] [Module ℂ OneForm]
variable (V : Type*) [AddCommGroup V] [Module ℂ V]

/-- Full nested symmetrized transport generated by a velocity-localized one-form test. -/
noncomputable def nestedVelocityTransportFlux
    (velocity m : V →ₗ[ℂ] V)
    (N : OneForm →ₗ[ℂ] (V →ₗ[ℂ] V)) :
    OneForm →ₗ[ℂ] (V →ₗ[ℂ] V) :=
  (_root_.ConservationLaw.symmetrizedProductRightLinear V m).comp
    (velocityLocalizationFlux V velocity N)

@[simp]
theorem nestedVelocityTransportFlux_apply
    (velocity m : V →ₗ[ℂ] V)
    (N : OneForm →ₗ[ℂ] (V →ₗ[ℂ] V)) (α : OneForm) :
    nestedVelocityTransportFlux V velocity m N α =
      _root_.ConservationLaw.symmetrizedProduct
        (_root_.ConservationLaw.symmetrizedProduct (N α) velocity) m :=
  rfl

/-- Flux obtained by pairing the symmetrized velocity current `1/2 {v,m}` with the localized
one-form test. -/
noncomputable def symmetrizedVelocityCurrentFlux
    (velocity m : V →ₗ[ℂ] V)
    (N : OneForm →ₗ[ℂ] (V →ₗ[ℂ] V)) :
    OneForm →ₗ[ℂ] (V →ₗ[ℂ] V) :=
  operatorLocalCurrentPairing V N (symmetrizedVelocityCurrent V velocity m)

@[simp]
theorem symmetrizedVelocityCurrentFlux_apply
    (velocity m : V →ₗ[ℂ] V)
    (N : OneForm →ₗ[ℂ] (V →ₗ[ℂ] V)) (α : OneForm) :
    symmetrizedVelocityCurrentFlux V velocity m N α =
      _root_.ConservationLaw.symmetrizedProduct (N α)
        (symmetrizedVelocityCurrent V velocity m) :=
  rfl

/-- Canonical correction to the symmetrized/conventional current flux.  It is defined as the
exact difference between the full nested transport and the flux represented by `1/2 {v,m}`. -/
noncomputable def localizationCorrectionFlux
    (velocity m : V →ₗ[ℂ] V)
    (N : OneForm →ₗ[ℂ] (V →ₗ[ℂ] V)) :
    OneForm →ₗ[ℂ] (V →ₗ[ℂ] V) :=
  nestedVelocityTransportFlux V velocity m N -
    symmetrizedVelocityCurrentFlux V velocity m N

/-- The localization correction is exactly the double commutator measuring failure of the
localized one-form operator to commute with the transported quantity. -/
@[simp]
theorem localizationCorrectionFlux_apply
    (velocity m : V →ₗ[ℂ] V)
    (N : OneForm →ₗ[ℂ] (V →ₗ[ℂ] V)) (α : OneForm) :
    localizationCorrectionFlux V velocity m N α =
      (1 / 4 : ℂ) • _root_.ConservationLaw.linearCommutator velocity
        (_root_.ConservationLaw.linearCommutator (N α) m) := by
  change
    _root_.ConservationLaw.symmetrizedProduct
        (_root_.ConservationLaw.symmetrizedProduct (N α) velocity) m -
      _root_.ConservationLaw.symmetrizedProduct (N α)
        (symmetrizedVelocityCurrent V velocity m) = _
  rw [symmetrizedVelocityTransport_decomposition V (N α) velocity m]
  module

/-- The full velocity-generated transport flux is the symmetrized/conventional current flux plus
the canonical localization correction. -/
theorem nestedVelocityTransportFlux_eq_current_add_correction
    (velocity m : V →ₗ[ℂ] V)
    (N : OneForm →ₗ[ℂ] (V →ₗ[ℂ] V)) :
    nestedVelocityTransportFlux V velocity m N =
      symmetrizedVelocityCurrentFlux V velocity m N +
        localizationCorrectionFlux V velocity m N := by
  apply LinearMap.ext
  intro α
  change _ = _ + (_ - _)
  module

/-- If every localized one-form operator commutes with `m`, the correction vanishes.  This is the
local/commuting corollary in which the symmetrized velocity current represents the full flux. -/
theorem localizationCorrectionFlux_eq_zero_of_commutes
    (velocity m : V →ₗ[ℂ] V)
    (N : OneForm →ₗ[ℂ] (V →ₗ[ℂ] V))
    (hcomm : ∀ α, _root_.ConservationLaw.linearCommutator (N α) m = 0) :
    localizationCorrectionFlux V velocity m N = 0 := by
  apply LinearMap.ext
  intro α
  rw [localizationCorrectionFlux_apply V velocity m N α, hcomm α]
  simp

/-- A velocity representation of localizer evolution lifts to the full nested transport flux for
an arbitrary transported operator `m`; no locality/commutation assumption on `m` is needed. -/
theorem factorsThroughDifferential_nestedVelocityTransportFlux
    (ℏ : ℝ) (h : V →ₗ[ℂ] V)
    (M : Test →ₗ[ℂ] (V →ₗ[ℂ] V))
    (m velocity : V →ₗ[ℂ] V)
    (d : Test →ₗ[ℂ] OneForm)
    (N : OneForm →ₗ[ℂ] (V →ₗ[ℂ] V))
    (hvelocity : _root_.ConservationLaw.FactorsThroughDifferential d
      (heisenbergLocalizationFunctional V ℏ h M)
      (velocityLocalizationFlux V velocity N)) :
    _root_.ConservationLaw.FactorsThroughDifferential d
      (heisenbergTransportFunctional V ℏ h M m)
      (nestedVelocityTransportFlux V velocity m N) := by
  rw [heisenbergTransportFunctional_eq_symmetrizedProductRight_comp V ℏ h M m]
  simpa [nestedVelocityTransportFlux] using
    (_root_.ConservationLaw.FactorsThroughDifferential.postcomp hvelocity
      (_root_.ConservationLaw.symmetrizedProductRightLinear V m))

/-- General representation theorem: intrinsic Heisenberg transport is represented by the
symmetrized/conventional current flux plus the canonical localization correction. -/
theorem factorsThroughDifferential_current_add_correction
    (ℏ : ℝ) (h : V →ₗ[ℂ] V)
    (M : Test →ₗ[ℂ] (V →ₗ[ℂ] V))
    (m velocity : V →ₗ[ℂ] V)
    (d : Test →ₗ[ℂ] OneForm)
    (N : OneForm →ₗ[ℂ] (V →ₗ[ℂ] V))
    (hvelocity : _root_.ConservationLaw.FactorsThroughDifferential d
      (heisenbergLocalizationFunctional V ℏ h M)
      (velocityLocalizationFlux V velocity N)) :
    _root_.ConservationLaw.FactorsThroughDifferential d
      (heisenbergTransportFunctional V ℏ h M m)
      (symmetrizedVelocityCurrentFlux V velocity m N +
        localizationCorrectionFlux V velocity m N) := by
  intro f
  rw [(factorsThroughDifferential_nestedVelocityTransportFlux
    V ℏ h M m velocity d N hvelocity) f]
  rw [nestedVelocityTransportFlux_eq_current_add_correction V velocity m N]
  rfl

/-- The corrected current functional is a chosen full differential-current representation of the
intrinsic transport. -/
noncomputable def correctedSymmetrizedVelocityCurrentRepresentation
    (ℏ : ℝ) (h : V →ₗ[ℂ] V)
    (M : Test →ₗ[ℂ] (V →ₗ[ℂ] V))
    (m velocity : V →ₗ[ℂ] V)
    (d : Test →ₗ[ℂ] OneForm)
    (N : OneForm →ₗ[ℂ] (V →ₗ[ℂ] V))
    (hvelocity : _root_.ConservationLaw.FactorsThroughDifferential d
      (heisenbergLocalizationFunctional V ℏ h M)
      (velocityLocalizationFlux V velocity N)) :
    _root_.ConservationLaw.DifferentialCurrentRepresentation d
      (heisenbergTransportFunctional V ℏ h M m) where
  current := symmetrizedVelocityCurrentFlux V velocity m N +
    localizationCorrectionFlux V velocity m N
  factors := factorsThroughDifferential_current_add_correction
    V ℏ h M m velocity d N hvelocity

/-- Any other full current functional representing the same intrinsic transport is equivalent on
exact differentials to `symmetrized current + localization correction`.  This isolates the
representation ambiguity away from `range d`. -/
theorem currentEquivalent_correctedSymmetrizedVelocity
    (ℏ : ℝ) (h : V →ₗ[ℂ] V)
    (M : Test →ₗ[ℂ] (V →ₗ[ℂ] V))
    (m velocity : V →ₗ[ℂ] V)
    (d : Test →ₗ[ℂ] OneForm)
    (N : OneForm →ₗ[ℂ] (V →ₗ[ℂ] V))
    (hvelocity : _root_.ConservationLaw.FactorsThroughDifferential d
      (heisenbergLocalizationFunctional V ℏ h M)
      (velocityLocalizationFlux V velocity N))
    (R : _root_.ConservationLaw.DifferentialCurrentRepresentation d
      (heisenbergTransportFunctional V ℏ h M m)) :
    _root_.ConservationLaw.DifferentialCurrentEquivalent d R.current
      (symmetrizedVelocityCurrentFlux V velocity m N +
        localizationCorrectionFlux V velocity m N) :=
  R.currentEquivalent
    (correctedSymmetrizedVelocityCurrentRepresentation
      V ℏ h M m velocity d N hvelocity)

end SingleParticle
end QuantumMechanics
