import Mathlib.Analysis.InnerProductSpace.Adjoint
import Mathlib.Analysis.Normed.Algebra.Exponential
import Mathlib.Analysis.SpecialFunctions.Exponential
import Mathlib.Analysis.Complex.RealDeriv
import Mathlib.Analysis.Calculus.FDeriv.CompCLM
import Mathlib.Analysis.Calculus.MeanValue
import Mathlib.Tactic

set_option linter.style.header false

/-!
# Unitary evolution of bounded self-adjoint operators

For a bounded operator `B` on a complex Hilbert space, the Banach-algebra exponential

`U_B(t) = exp (-i t B)`

defines a norm-continuous one-parameter group. When `B` is self-adjoint the evolution is unitary,
preserves vector norms, and satisfies the displacement estimate
`‖U_B(t)x - x‖ ≤ ‖B x‖ |t|`. For commuting bounded generators, evolution under their sum factors
into the product of the individual evolutions. This module is independent of the unbounded Stone
construction so bounded quantum-dynamics layers can reuse the same operator-theoretic API.
-/

namespace LinearPMap

noncomputable section

open Complex
open scoped InnerProductSpace

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

private noncomputable def unitaryTimeCoefficient (t : ℝ) : ℂ :=
  -((t : ℂ) * I)

private theorem unitaryTimeCoefficient_zero : unitaryTimeCoefficient 0 = 0 := by
  simp [unitaryTimeCoefficient]

private theorem unitaryTimeCoefficient_add (t s : ℝ) :
    unitaryTimeCoefficient (t + s) = unitaryTimeCoefficient t + unitaryTimeCoefficient s := by
  simp [unitaryTimeCoefficient]
  ring

private theorem star_unitaryTimeCoefficient (t : ℝ) :
    star (unitaryTimeCoefficient t) = unitaryTimeCoefficient (-t) := by
  simp [unitaryTimeCoefficient]

/-- The bounded Schrödinger evolution generated by a bounded operator `B`. -/
noncomputable def boundedUnitaryEvolution (B : H →L[ℂ] H) (t : ℝ) : H →L[ℂ] H :=
  NormedSpace.exp (unitaryTimeCoefficient t • B)

omit [CompleteSpace H] in
/-- Unfold the bounded evolution to the explicit Schrödinger exponential. -/
theorem boundedUnitaryEvolution_eq_exp (B : H →L[ℂ] H) (t : ℝ) :
    boundedUnitaryEvolution B t = NormedSpace.exp (-((t : ℂ) * I) • B) := by
  rfl

omit [CompleteSpace H] in
@[simp]
theorem boundedUnitaryEvolution_zero (B : H →L[ℂ] H) :
    boundedUnitaryEvolution B 0 = 1 := by
  simp [boundedUnitaryEvolution, unitaryTimeCoefficient_zero]

/-- Exponentials of scalar multiples of one bounded operator form a one-parameter group. -/
theorem boundedUnitaryEvolution_add (B : H →L[ℂ] H) (t s : ℝ) :
    boundedUnitaryEvolution B (t + s) =
      boundedUnitaryEvolution B t * boundedUnitaryEvolution B s := by
  change NormedSpace.exp (unitaryTimeCoefficient (t + s) • B) =
      NormedSpace.exp (unitaryTimeCoefficient t • B) *
      NormedSpace.exp (unitaryTimeCoefficient s • B)
  rw [unitaryTimeCoefficient_add, add_smul]
  let +nondep : NormedAlgebra ℚ (H →L[ℂ] H) :=
    .restrictScalars ℚ ℂ (H →L[ℂ] H)
  exact NormedSpace.exp_add_of_commute (𝔸 := H →L[ℂ] H)
    (((Commute.refl B).smul_left (unitaryTimeCoefficient t)).smul_right
      (unitaryTimeCoefficient s))

/-- Evolutions generated by commuting bounded operators factor through the sum of generators. -/
theorem boundedUnitaryEvolution_add_generator_of_commute
    (B C : H →L[ℂ] H) (hBC : Commute B C) (t : ℝ) :
    boundedUnitaryEvolution (B + C) t =
      boundedUnitaryEvolution B t * boundedUnitaryEvolution C t := by
  unfold boundedUnitaryEvolution
  rw [smul_add]
  let +nondep : NormedAlgebra ℚ (H →L[ℂ] H) :=
    .restrictScalars ℚ ℂ (H →L[ℂ] H)
  exact NormedSpace.exp_add_of_commute (𝔸 := H →L[ℂ] H)
    ((hBC.smul_left _).smul_right _)

/-- For self-adjoint `B`, the adjoint evolution is evolution at negative time. -/
theorem boundedUnitaryEvolution_star
    (B : H →L[ℂ] H) (hB : IsSelfAdjoint B) (t : ℝ) :
    star (boundedUnitaryEvolution B t) = boundedUnitaryEvolution B (-t) := by
  have hBstar : star B = B := by
    simpa only [isSelfAdjoint_iff] using hB
  simp [boundedUnitaryEvolution, NormedSpace.star_exp, hBstar, star_unitaryTimeCoefficient]

/-- A bounded self-adjoint exponential is unitary. -/
private theorem boundedUnitaryEvolution_mem_unitary
    (B : H →L[ℂ] H) (hB : IsSelfAdjoint B) (t : ℝ) :
    boundedUnitaryEvolution B t ∈ unitary (H →L[ℂ] H) := by
  let +nondep : NormedAlgebra ℚ (H →L[ℂ] H) :=
    .restrictScalars ℚ ℂ (H →L[ℂ] H)
  apply NormedSpace.exp_mem_unitary_of_mem_skewAdjoint
  exact hB.smul_mem_skewAdjoint (by
    rw [skewAdjoint.mem_iff]
    simp [unitaryTimeCoefficient])

/-- The bounded exponential group is continuous in operator norm, hence in particular strongly
continuous on every vector. -/
theorem boundedUnitaryEvolution_continuous (B : H →L[ℂ] H) :
    Continuous (boundedUnitaryEvolution B) := by
  let +nondep : NormedAlgebra ℚ (H →L[ℂ] H) :=
    .restrictScalars ℚ ℂ (H →L[ℂ] H)
  unfold boundedUnitaryEvolution unitaryTimeCoefficient
  exact NormedSpace.exp_continuous.comp (by fun_prop)

/-- The operator-norm derivative of the bounded unitary evolution. -/
private theorem boundedUnitaryEvolution_hasDerivAt (B : H →L[ℂ] H) (t : ℝ) :
    HasDerivAt (fun τ : ℝ => boundedUnitaryEvolution B τ)
      (boundedUnitaryEvolution B t * ((-I : ℂ) • B)) t := by
  have hc :=
    hasDerivAt_exp_smul_const ((-I : ℂ) • B) (t : ℂ)
  have hr := (hc.hasFDerivAt.restrictScalars ℝ).comp t Complex.ofRealCLM.hasFDerivAt
  have hd := hr.hasDerivAt
  simpa [Function.comp_def, boundedUnitaryEvolution, unitaryTimeCoefficient, smul_smul] using hd

/-- The bounded-generator differential equation after evaluating the propagator on a vector. -/
theorem boundedUnitaryEvolution_apply_hasDerivAt (B : H →L[ℂ] H) (t : ℝ) (x : H) :
    HasDerivAt (fun τ : ℝ => boundedUnitaryEvolution B τ x)
      ((boundedUnitaryEvolution B t * ((-I : ℂ) • B)) x) t := by
  have h := (((ContinuousLinearMap.apply ℂ H) x).restrictScalars ℝ).hasFDerivAt.comp t
    (boundedUnitaryEvolution_hasDerivAt B t).hasFDerivAt
  simpa [Function.comp_def] using h.hasDerivAt

/-- A bounded self-adjoint exponential preserves the norm of every vector. -/
theorem boundedUnitaryEvolution_apply_norm
    (B : H →L[ℂ] H) (hB : IsSelfAdjoint B) (t : ℝ) (x : H) :
    ‖boundedUnitaryEvolution B t x‖ = ‖x‖ := by
  exact ContinuousLinearMap.norm_map_of_mem_unitary
    (boundedUnitaryEvolution_mem_unitary B hB t) x

/-- The displacement under bounded self-adjoint evolution is controlled by the generator on the
initial vector. -/
theorem norm_boundedUnitaryEvolution_apply_sub_le
    (B : H →L[ℂ] H) (hB : IsSelfAdjoint B) (t : ℝ) (x : H) :
    ‖boundedUnitaryEvolution B t x - x‖ ≤ ‖B x‖ * |t| := by
  have hderiv : ∀ τ ∈ (Set.univ : Set ℝ),
      HasDerivWithinAt (fun s : ℝ => boundedUnitaryEvolution B s x)
        ((boundedUnitaryEvolution B τ * ((-I : ℂ) • B)) x) Set.univ τ := by
    intro τ _
    exact (boundedUnitaryEvolution_apply_hasDerivAt B τ x).hasDerivWithinAt
  have hbound : ∀ τ ∈ (Set.univ : Set ℝ),
      ‖((boundedUnitaryEvolution B τ * ((-I : ℂ) • B)) x)‖ ≤ ‖B x‖ := by
    intro τ _
    change ‖boundedUnitaryEvolution B τ (((-I : ℂ) • B) x)‖ ≤ ‖B x‖
    rw [boundedUnitaryEvolution_apply_norm B hB τ]
    change ‖(-I : ℂ) • B x‖ ≤ ‖B x‖
    rw [norm_smul]
    simp
  have hmv := Convex.norm_image_sub_le_of_norm_hasDerivWithin_le
    (f := fun s : ℝ => boundedUnitaryEvolution B s x)
    (f' := fun τ : ℝ => (boundedUnitaryEvolution B τ * ((-I : ℂ) • B)) x)
    (s := Set.univ) (x := (0 : ℝ)) (y := t)
    hderiv hbound convex_univ (Set.mem_univ 0) (Set.mem_univ t)
  simpa using hmv

end

end LinearPMap
