import LeanCondensedMatter.Combinatorics.FiniteIndex.DeletedPositions
import LeanCondensedMatter.Combinatorics.FiniteIndex.DeletedPositionsSuccAbove
import LeanCondensedMatter.Combinatorics.FiniteIndex.EraseIdxOfFn
import LeanCondensedMatter.Combinatorics.BinaryShuffle
import LeanCondensedMatter.Combinatorics.BlockPermutationSign
import LeanCondensedMatter.Combinatorics.BinaryShuffleSlotEquiv
import LeanCondensedMatter.Combinatorics.BinaryShuffleSlots
import LeanCondensedMatter.Combinatorics.FamilySlotShuffle
import LeanCondensedMatter.Combinatorics.FamilySlotShuffleDecomposition
import LeanCondensedMatter.Combinatorics.IncidenceAlgebra.Mobius
import LeanCondensedMatter.Combinatorics.SetPartition.Refinement
import LeanCondensedMatter.Combinatorics.SetPartition.Coarsening
import LeanCondensedMatter.Combinatorics.SetPartition.Mobius
import LeanCondensedMatter.Combinatorics.SetPartition.DistinguishedBlock
import LeanCondensedMatter.Combinatorics.SetPartition.MobiusFormula
import LeanCondensedMatter.Combinatorics.Cumulant.Moment
import LeanCondensedMatter.Combinatorics.Cumulant.Inversion
import LeanCondensedMatter.Combinatorics.Cumulant.Normalized
import LeanCondensedMatter.Combinatorics.Cumulant.Independence
import LeanCondensedMatter.Combinatorics.Cumulant.ConnectedDecomposition
import LeanCondensedMatter.Combinatorics.Cumulant.ConnectedDecompositionInversion
import LeanCondensedMatter.Combinatorics.PerfectPairing
import LeanCondensedMatter.Combinatorics.PerfectPairing.ExchangeSum
import LeanCondensedMatter.Combinatorics.PermutationOrbitPartition
import LeanCondensedMatter.Combinatorics.PermutationConnectedDecomposition
import LeanCondensedMatter.Combinatorics.PermutationCumulant
import LeanCondensedMatter.Combinatorics.SubsetSplit
import LeanCondensedMatter.Combinatorics.InvolutionCard

set_option linter.style.header false

/-!
# Combinatorics

Public entry point for the project's pure finite combinatorics. The implementation is organized
around finite-index operations, shuffles, set partitions and cumulants, perfect pairings, and the
exchange-weighted pairing/permutation-sum backend.
-/
