import LeanCondensedMatter.Combinatorics.FiniteIndex
import LeanCondensedMatter.Combinatorics.SumEquivPartition
import LeanCondensedMatter.Combinatorics.BinaryShuffle
import LeanCondensedMatter.Combinatorics.BinaryShuffleSlotEquiv
import LeanCondensedMatter.Combinatorics.BinaryShuffleSlots
import LeanCondensedMatter.Combinatorics.FamilySlotShuffle
import LeanCondensedMatter.Combinatorics.FamilySlotShuffleDecomposition
import LeanCondensedMatter.Combinatorics.FinpartitionOrderShuffle
import LeanCondensedMatter.Combinatorics.SimpleGraphComponentPartition
import LeanCondensedMatter.Combinatorics.IncidenceAlgebra
import LeanCondensedMatter.Combinatorics.SetPartition
import LeanCondensedMatter.Combinatorics.Cumulant
import LeanCondensedMatter.Combinatorics.PerfectPairing
import LeanCondensedMatter.Combinatorics.SubsetSplit
import LeanCondensedMatter.Combinatorics.InvolutionCard

set_option linter.style.header false

/-!
# Combinatorics

Finite combinatorics used throughout the project: finite-index operations, shuffles, finite and
graph-component partitions, incidence algebra, cumulants, perfect pairings, subset decompositions,
and
involution-cardinality results.

Exchange-weighted permutation theory is developed separately in `LeanCondensedMatter.Permutation`.
-/
