import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.SchrodingerContinuity
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.ProbabilityIntegral1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.SchrodingerMinimalCoupling1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.SchrodingerGaugeCurrent1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.SchrodingerGaugeContinuity1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.SchrodingerGaugeContinuityWeak1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.SchrodingerContinuityFiniteDimensional
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.SchrodingerContinuityWeak1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.SchrodingerContinuitySmeared1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.SchrodingerContinuityCompactSupport1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.SchrodingerContinuitySchwartz1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.SchrodingerContinuitySchwartzTotal1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.SchrodingerProbabilityConservation1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.L2Multiplication1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.L2SmearedProbabilityDensity1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.SchrodingerHamiltonian1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.SchrodingerHamiltonianAnalytic1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.SchrodingerHamiltonianClosed1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.SchrodingerHamiltonianRegularity1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.SchrodingerHamiltonianClosedH21D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.SchrodingerHamiltonianLaplacianSymmetry1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.SchrodingerHamiltonianFullSymmetry1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.SchrodingerHamiltonianSelfAdjointCriterion1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.SchrodingerHamiltonianLaplacianSelfAdjoint1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.SchrodingerHamiltonianSelfAdjoint1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.SchrodingerEvolution1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.SchrodingerStoneEvolution1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.SchrodingerEvolutionProbability1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.SchrodingerEvolutionContinuity1D

set_option linter.style.header false

/-!
# Quantum mechanics

Public entry point for concrete first-quantized quantum mechanics. The current public realization is
the one-particle continuum Schrödinger stack under `QuantumMechanics.SingleParticle.Continuum`.

Generic state and response theory remains upstream in `QuantumTheory`. Implementation modules should
continue to import the narrow concrete modules they use rather than this public umbrella.
-/
