import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.Continuity.Scalar1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.Probability.Integral1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.SchrodingerMinimalCoupling1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.SchrodingerGaugeCurrent1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.SchrodingerGaugeContinuity1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.SchrodingerGaugeContinuityWeak1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.Continuity.FiniteDimensional
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.Continuity.Weak1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.Continuity.Smeared1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.SchrodingerContinuityCompactSupport1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.SchrodingerContinuitySchwartz1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.SchrodingerContinuitySchwartzTotal1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.SchrodingerProbabilityConservation1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.L2.Multiplication1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.L2.Probability1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.Hamiltonian.Basic1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.Hamiltonian.DenseDomain1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.Hamiltonian.MaximalLaplacian1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.Hamiltonian.Regularity1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.Hamiltonian.Closed1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.Hamiltonian.LaplacianSymmetry1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.Hamiltonian.Symmetry1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.Hamiltonian.SelfAdjointCriterion1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.Hamiltonian.LaplacianSelfAdjoint1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.Hamiltonian.SelfAdjoint1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.Evolution.Interface1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.Evolution.Stone1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.Evolution.Probability1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.Continuum.Evolution.RepresentativeContinuity1D

set_option linter.style.header false

/-!
# Quantum mechanics

Public entry point for concrete first-quantized quantum mechanics. The current public realization is
the one-particle continuum Schrödinger stack under `QuantumMechanics.SingleParticle.Continuum`.

Generic state and response theory remains upstream in `QuantumTheory`. Implementation modules should
continue to import the narrow concrete modules they use rather than this public umbrella.
-/
