import LeanCondensedMatter.SecondQuantization.Common.CompletedSpace.Basic
import LeanCondensedMatter.SecondQuantization.Common.CompletedSpace.CoordinateIsometry
import LeanCondensedMatter.SecondQuantization.Common.CompletedSpace.CoordinateProjection
import LeanCondensedMatter.SecondQuantization.Common.CompletedSpace.Diagonal
import LeanCondensedMatter.SecondQuantization.Common.CompletedSpace.DiagonalAnalytic
import LeanCondensedMatter.SecondQuantization.Common.CompletedSpace.FiniteCompatibility
import LeanCondensedMatter.SecondQuantization.Common.CompletedSpace.FiniteThermalCompatibility

set_option linter.style.header false

/-!
# Completed Fock-space infrastructure

Statistics-independent completed-space, coordinate-isometry, diagonal, and finite-compatibility infrastructure.
-/
