import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.PairingEvaluation
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.VertexLabel
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.QuarticOperator
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.Leg
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.Diagram
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.TwoPoint
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.TwoPointComponentPartition
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.TwoPointComponentRestriction
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.TwoPointExternalConnectivity
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.TwoPointExternalRestriction
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.TwoPointComponentDecomposition
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.TwoPointComponentVertexProduct
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.TwoPointComponentOrderedSimplex
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.TwoPointCanonicalComponentShuffle
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.TwoPointComponentPairProduct
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.TwoPointRestrictedPairEquiv
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.TwoPointRestrictedPairOrientation
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.Ordered
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.Connected
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.ComponentPartition
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.ComponentRestriction
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.ComponentOrder
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.ComponentOrderDecomposition
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.ComponentOrderedSimplex
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.TwoComponentOrderedSimplex
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.FiniteComponentOrderedSimplex
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.ComponentOrderedSimplexProduct
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.ComponentVertexProduct
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.ComponentConnected
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.Reassemble
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.ReassembleComponentPartitionEq
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.ReassembleRestrictComponent
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.ReassembleDecompose
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.ComponentDecompositionEquiv

set_option linter.style.header false

/-!
# Statistics-independent diagrammatics

Scalar evaluation of perfect pairings from caller-supplied weights and pair kernels; quartic vertex
labels, shared local-leg semantics and operator constructors, leg indexing, two-point diagrams with
distinguished external legs, full component partitions, automatic connectivity of the two one-legged
external vertices, vacuum/external component restriction data, the canonical external-plus-vacuum
decomposition of component indices and interaction vertices, componentwise interaction-vertex
products and Dyson signs, order-preserving shuffles, the canonical shuffle induced by the original
interaction-vertex order, local-time reconstruction, and ordered-simplex products for component
interaction-time slots, componentwise normalized-pair sums and products, equivalences between ambient
component pairs and restricted external/vacuum pairings, and the resulting pair-orientation
dichotomy; ordered diagram data, connected components, component-local orders, order-preserving
shuffle decompositions, and shuffled ordered-simplex integrands; quartic component restriction and
reassembly, decomposition equivalences, and componentwise scalar factorization.
-/
