import LeanCondensedMatter.SecondQuantization.Common.ImaginaryTime.TimeOrdering
import LeanCondensedMatter.SecondQuantization.Common.ImaginaryTime.DiagonalEvolution
import LeanCondensedMatter.SecondQuantization.Common.ImaginaryTime.EnergyShift
import LeanCondensedMatter.SecondQuantization.Common.ImaginaryTime.InteractionPicture
import LeanCondensedMatter.SecondQuantization.Common.ImaginaryTime.KMSRotation
import LeanCondensedMatter.SecondQuantization.Common.ImaginaryTime.Quartic
import LeanCondensedMatter.SecondQuantization.Common.ImaginaryTime.ExternalInsertionMixedOrder
import LeanCondensedMatter.SecondQuantization.Common.ImaginaryTime.TwoPointMixedOrder
import LeanCondensedMatter.SecondQuantization.Common.ImaginaryTime.MixedEventSlotEmbedding
import LeanCondensedMatter.SecondQuantization.Common.ImaginaryTime.MixedOrderChamber
import LeanCondensedMatter.SecondQuantization.Common.ImaginaryTime.MixedOrderWallMeasure
import LeanCondensedMatter.SecondQuantization.Common.ImaginaryTime.MixedOrderSignature
import LeanCondensedMatter.SecondQuantization.Common.ImaginaryTime.TwoPointMixedLegOrder
import LeanCondensedMatter.SecondQuantization.Common.ImaginaryTime.TwoPointInteractionRelabel
import LeanCondensedMatter.SecondQuantization.Common.ImaginaryTime.TwoPointInteractionRelabelTime
import LeanCondensedMatter.SecondQuantization.Common.ImaginaryTime.TwoPointInteractionRelabelMixedPosition

set_option linter.style.header false

/-!
# Statistics-independent imaginary-time infrastructure

Statistics-aware pair time ordering, basis-diagonal free evolution, fixed energy-shift eigenoperators,
algebraic Heisenberg evolution, interaction-picture operators, KMS rotation identities, generic
quartic-interaction evolution, the arbitrary-external mixed event/leg order, and the
statistics-independent mixed two-point event/leg order with
monotone slot transport, interaction-slot relabeling and mixed-position covariance, order chambers,
null walls, and measurable finite signatures.
-/
