import LeanCondensedMatter.SecondQuantization.Common.Perturbation.FiniteOperatorIntegral
import LeanCondensedMatter.SecondQuantization.Common.Perturbation.FiniteAnalyticBridge
import LeanCondensedMatter.SecondQuantization.Common.Perturbation.DysonExpansion
import LeanCondensedMatter.SecondQuantization.Common.Perturbation.ContinuousDyson
import LeanCondensedMatter.SecondQuantization.Common.Perturbation.ContinuousDysonBounds
import LeanCondensedMatter.SecondQuantization.Common.Perturbation.AnalyticDyson
import LeanCondensedMatter.SecondQuantization.Common.Perturbation.AnalyticDysonVolterra
import LeanCondensedMatter.SecondQuantization.Common.Perturbation.AnalyticDysonExponential
import LeanCondensedMatter.SecondQuantization.Common.Perturbation.AnalyticDysonExponentialIdentity
import LeanCondensedMatter.SecondQuantization.Common.Perturbation.AnalyticDysonExponentialUniqueness
import LeanCondensedMatter.SecondQuantization.Common.Perturbation.DysonTimeIndependent
import LeanCondensedMatter.SecondQuantization.Common.Perturbation.DysonTraceSeries
import LeanCondensedMatter.SecondQuantization.Common.Perturbation.AnalyticDysonTrace

set_option linter.style.header false

/-!
# Finite-basis perturbative infrastructure

Coefficientwise interval integration, its finite-dimensional continuous-operator realization,
statistics-independent algebraic and continuous Dyson coefficients, factorial norm majorants,
the norm-convergent analytic Dyson evolution, its Volterra equation and exact operator-exponential
identity, the algebraic and analytic time-independent specialization, convergent finite trace series,
and finite trace power series for endomorphisms on a finite configuration basis.
-/
