import LeanCondensedMatter.SecondQuantization.Common.Perturbation.FiniteOperatorIntegral
import LeanCondensedMatter.SecondQuantization.Common.Perturbation.FiniteAnalyticBridge
import LeanCondensedMatter.SecondQuantization.Common.Perturbation.DysonExpansion
import LeanCondensedMatter.SecondQuantization.Common.Perturbation.ContinuousDyson
import LeanCondensedMatter.SecondQuantization.Common.Perturbation.ContinuousDysonBounds
import LeanCondensedMatter.SecondQuantization.Common.Perturbation.AnalyticDyson
import LeanCondensedMatter.SecondQuantization.Common.Perturbation.AnalyticDysonVolterra
import LeanCondensedMatter.SecondQuantization.Common.Perturbation.AnalyticDysonExponential
import LeanCondensedMatter.SecondQuantization.Common.Perturbation.DysonExpansionVerification
import LeanCondensedMatter.SecondQuantization.Common.Perturbation.DysonTraceSeries

set_option linter.style.header false

/-!
# Finite-basis perturbative infrastructure

Coefficientwise interval integration, its finite-dimensional continuous-operator realization,
statistics-independent algebraic and continuous Dyson coefficients, factorial norm majorants,
the norm-convergent analytic Dyson evolution, its Volterra equation and exact operator-exponential
candidate, and finite trace power series for endomorphisms on a finite configuration basis.
-/
