import LeanCondensedMatter.SecondQuantization.Common.Perturbation.MatrixCoefficientDyson
import LeanCondensedMatter.SecondQuantization.Common.Perturbation.FiniteOperatorIntegral
import LeanCondensedMatter.SecondQuantization.Common.Perturbation.FiniteAnalyticBridge
import LeanCondensedMatter.SecondQuantization.Common.Perturbation.DysonExpansion
import LeanCondensedMatter.SecondQuantization.Common.Perturbation.ContinuousDyson
import LeanCondensedMatter.SecondQuantization.Common.Perturbation.ContinuousDysonBounds
import LeanCondensedMatter.SecondQuantization.Common.Perturbation.AnalyticDyson
import LeanCondensedMatter.SecondQuantization.Common.Perturbation.AnalyticDysonVolterra
import LeanCondensedMatter.SecondQuantization.Common.Perturbation.AnalyticDysonExponential
import LeanCondensedMatter.SecondQuantization.Common.Perturbation.AnalyticDysonExponentialIdentity
import LeanCondensedMatter.SecondQuantization.Common.Perturbation.AnalyticDysonExponentialUniqueness
import LeanCondensedMatter.SecondQuantization.Common.Perturbation.DysonTimeIndependent
import LeanCondensedMatter.SecondQuantization.Common.Perturbation.DysonTraceSeries
import LeanCondensedMatter.SecondQuantization.Common.Perturbation.AnalyticDysonTrace

set_option linter.style.header false

/-!
# Perturbative infrastructure

The public layer includes a matrix-coefficient first-Dyson boundary valid for arbitrary
configuration types.  The remaining operator-valued integration, continuous-operator realization,
full Dyson recursion, norm bounds, analytic evolution, trace series, and exponential identities are
finite-basis constructions and retain their explicit finiteness assumptions.
-/
