import LeanCondensedMatter.Transport.AnomalousHall.MassiveDirac
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracSpectral
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBerryBridge
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBerrySymmetry
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracIntrinsic
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracIntrinsicConductivity
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracStreda
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracStredaSpectral
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinBerry
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinBands
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinLimit
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinLorentzian
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinOccupation
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinTail
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinFiniteWindow
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinFermiSurface
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinSpectator
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinInterband
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleFactor
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleWindow
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleContinuity
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleWindowContinuity
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleWindowBound
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleLocalError
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleErrorIntegral
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleInnerError
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleOuterError
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleErrorSplit
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleErrorBound
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleErrorLimit
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleExtraction
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleExtractionLimit

set_option linter.style.header false

/-!
# Anomalous Hall transport benchmarks

Public entry point for clean and disordered anomalous-Hall model benchmarks.  Generic spectral and
linear-response infrastructure remains owned by `Analysis` and the generic `Transport` leaves;
this namespace contains concrete transport models that consume those layers.
-/
