import LeanCondensedMatter.Transport.AnomalousHall.MassiveDirac
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracCurrentBridge
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracSpectral
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBerryBridge
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBerrySymmetry
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracIntrinsic
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracIntrinsicConductivity
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracStreda
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracStredaIntegral
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracStredaZeroTemperature
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracStredaZeroTemperatureBoundary
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracStredaSurfaceSpectral
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracStredaSurfacePoleFactor
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracStredaSurfacePoleContinuity
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracCurrentOperatorBridge
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracStredaSpectral
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinBerry
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinBands
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinLimit
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinLorentzian
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinOccupation
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinTail
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinFiniteWindow
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinFermiSurface
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinSpectator
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinInterband
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleFactor
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleWindow
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleContinuity
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleWindowContinuity
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleWindowBound
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleLocalError
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleErrorIntegral
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleInnerError
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleOuterError
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleErrorSplit
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleErrorBound
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleErrorLimit
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleExtraction
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleExtractionLimit
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPairIntegral
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPairBerry
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinRadialDomination
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinRadialLimitInterchange
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinRadialSpectatorBound
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinRadialResolventBound
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinRadialSpectatorUniformBound
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinRadialPairUniformBound
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinRadialDominatedConvergence
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinRadialEnergyBridge
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinZeroTemperaturePair
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinZeroTemperaturePoleWeight
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinZeroTemperaturePoleErrorBound
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinZeroTemperaturePoleErrorLimit
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinZeroTemperaturePoleExtraction
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinZeroTemperaturePairLimit
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinZeroTemperatureRadialDCT
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinZeroTemperatureSharpRadial
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinZeroTemperatureFermiRadius
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinZeroTemperatureMetallicFermiRadius
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinZeroTemperatureSharpShell
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinZeroTemperatureConductivity
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinZeroTemperatureUV
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinCleanConductivity

set_option linter.style.header false

/-!
# Anomalous Hall transport benchmarks

Public entry point for clean and disordered anomalous-Hall model benchmarks. Generic spectral,
intrinsic-current, and linear-response infrastructure remains owned upstream; this namespace
contains concrete transport models and theorem-level bridges that consume those layers, including
the explicit zero-temperature pole-extraction and radial-limit chain used by the massive-Dirac Hall
benchmark. The finite-cutoff radial DCT remains separate from the ultraviolet-limit step.
-/
