import LeanCondensedMatter.Analysis.Operator.SchwartzSpinor1D
import LeanCondensedMatter.QuantumMechanics.SingleParticle.SymmetrizedVelocityCurrent

set_option linter.style.header false

/-!
# Spin-current representation on one-dimensional Schwartz spinors

This module realizes the internal-spin specialization requested by #1159. The one-particle space is
the two-component Schwartz spinor model from `Analysis.Operator.SchwartzSpinor1D`. Spatial
localization and velocity act componentwise, while `S_a = ℏ σ_a / 2` acts only on the internal
`Fin 2` index.

Consequently localization commutes with spin, so the generalized transport functional has the
symmetrized velocity-current representation

```text
j^(S_a) = 1/2 {v, S_a}.
```

This operator is often called the conventional spin current in the physics literature, but the
transport functional is the primary object here. In this spinor model `v` also commutes with
`S_a`, hence the chosen current density simplifies further to `v S_a`. An arbitrary internal
Hamiltonian matrix is retained; its commutator with `S_a` supplies the local source/torque term.
-/

namespace QuantumMechanics
namespace SingleParticle
namespace Continuum

open QuantumTheory.ConservationLaw

noncomputable section

/-- Concrete two-component Schwartz one-particle space. -/
abbrev SchwartzSpinorOneParticle1D := SchwartzSpinor1D.Spinor

/-- The spinor Schrödinger localization transport factors through the scalar Schwartz derivative,
with flux generated by the componentwise velocity operator. -/
theorem schwartzSpinorHeisenbergLocalizationFactorsThroughDifferential1D
    (ℏ κ : ℝ) (potential : SchwartzSpinor1D.Spatial)
    (internalH : SchwartzSpinor1D.SpinMatrix) :
    _root_.ConservationLaw.FactorsThroughDifferential
      SchwartzSpinor1D.derivative
      (heisenbergLocalizationFunctional SchwartzSpinorOneParticle1D ℏ
        (SchwartzSpinor1D.hamiltonian κ potential internalH)
        SchwartzSpinor1D.multiplicationLinear)
      (velocityLocalizationFlux SchwartzSpinorOneParticle1D
        (SchwartzSpinor1D.velocityOperator ℏ κ)
        SchwartzSpinor1D.multiplicationLinear) := by
  intro f
  simpa [heisenbergLocalizationFunctional, heisenbergScale,
    localizationCommutatorFunctional, _root_.ConservationLaw.linearCommutator,
    velocityLocalizationFlux, symmetrizedProductRightLinear,
    _root_.ConservationLaw.symmetrizedProduct] using
    (SchwartzSpinor1D.heisenberg_localization_eq_symmetrized_velocity
      ℏ κ potential internalH f)

/-- Multiplication localization commutes with a concrete spin component. -/
theorem schwartzSpin_localization_commutator_eq_zero
    (f : SchwartzSpinor1D.Spatial) (ℏ : ℝ) (axis : SchwartzSpinor1D.SpinAxis) :
    _root_.ConservationLaw.linearCommutator
      (SchwartzSpinor1D.multiplicationOperator f)
      (SchwartzSpinor1D.spinOperator ℏ axis) = 0 := by
  exact sub_eq_zero.mpr
    (SchwartzSpinor1D.multiplicationOperator_comp_spinOperator_comm f ℏ axis)

/-- The symmetrized velocity-current representation of spin transport on the Schwartz model. -/
noncomputable def schwartzSpinCurrentRepresentation1D
    (ℏ κ : ℝ) (potential : SchwartzSpinor1D.Spatial)
    (internalH : SchwartzSpinor1D.SpinMatrix) (axis : SchwartzSpinor1D.SpinAxis) :
    _root_.ConservationLaw.LocalCurrentDensityRepresentation
      SchwartzSpinor1D.derivative
      (heisenbergTransportFunctional SchwartzSpinorOneParticle1D ℏ
        (SchwartzSpinor1D.hamiltonian κ potential internalH)
        SchwartzSpinor1D.multiplicationLinear
        (SchwartzSpinor1D.spinOperator ℏ axis))
      (operatorLocalCurrentPairing SchwartzSpinorOneParticle1D
        SchwartzSpinor1D.multiplicationLinear) :=
  symmetrizedVelocityCurrentRepresentation SchwartzSpinorOneParticle1D ℏ
    (SchwartzSpinor1D.hamiltonian κ potential internalH)
    SchwartzSpinor1D.multiplicationLinear
    (SchwartzSpinor1D.spinOperator ℏ axis)
    (SchwartzSpinor1D.velocityOperator ℏ κ)
    SchwartzSpinor1D.derivative
    SchwartzSpinor1D.multiplicationLinear
    (schwartzSpinorHeisenbergLocalizationFactorsThroughDifferential1D
      ℏ κ potential internalH)
    (fun α => schwartzSpin_localization_commutator_eq_zero α ℏ axis)

@[simp]
theorem schwartzSpinCurrentRepresentation1D_currentDensity
    (ℏ κ : ℝ) (potential : SchwartzSpinor1D.Spatial)
    (internalH : SchwartzSpinor1D.SpinMatrix) (axis : SchwartzSpinor1D.SpinAxis) :
    (schwartzSpinCurrentRepresentation1D ℏ κ potential internalH axis).currentDensity =
      symmetrizedVelocityCurrent SchwartzSpinorOneParticle1D
        (SchwartzSpinor1D.velocityOperator ℏ κ)
        (SchwartzSpinor1D.spinOperator ℏ axis) :=
  rfl

/-- In the internal-spin model the velocity and spin operators commute. -/
theorem schwartzSpin_velocity_commutator_eq_zero
    (ℏ κ : ℝ) (axis : SchwartzSpinor1D.SpinAxis) :
    _root_.ConservationLaw.linearCommutator
      (SchwartzSpinor1D.velocityOperator ℏ κ)
      (SchwartzSpinor1D.spinOperator ℏ axis) = 0 := by
  exact sub_eq_zero.mpr
    (SchwartzSpinor1D.velocityOperator_comp_spinOperator_comm ℏ κ axis)

/-- The symmetrized spin current simplifies from `1/2 {v,S_a}` to `v S_a`. -/
theorem symmetrizedSpinCurrent_eq_velocity_comp_spin
    (ℏ κ : ℝ) (axis : SchwartzSpinor1D.SpinAxis) :
    symmetrizedVelocityCurrent SchwartzSpinorOneParticle1D
        (SchwartzSpinor1D.velocityOperator ℏ κ)
        (SchwartzSpinor1D.spinOperator ℏ axis) =
      (SchwartzSpinor1D.velocityOperator ℏ κ).comp
        (SchwartzSpinor1D.spinOperator ℏ axis) := by
  exact _root_.ConservationLaw.symmetrizedProduct_eq_comp_of_commutes
    (SchwartzSpinor1D.velocityOperator ℏ κ)
    (SchwartzSpinor1D.spinOperator ℏ axis)
    (schwartzSpin_velocity_commutator_eq_zero ℏ κ axis)

/-- Compatibility theorem retaining the conventional-spin-current wording. -/
theorem conventionalSpinCurrent_eq_velocity_comp_spin
    (ℏ κ : ℝ) (axis : SchwartzSpinor1D.SpinAxis) :
    symmetrizedVelocityCurrent SchwartzSpinorOneParticle1D
        (SchwartzSpinor1D.velocityOperator ℏ κ)
        (SchwartzSpinor1D.spinOperator ℏ axis) =
      (SchwartzSpinor1D.velocityOperator ℏ κ).comp
        (SchwartzSpinor1D.spinOperator ℏ axis) :=
  symmetrizedSpinCurrent_eq_velocity_comp_spin ℏ κ axis

/-- The current density stored in the local representation is exactly `v S_a`. -/
theorem schwartzSpinCurrentRepresentation1D_currentDensity_eq_velocity_comp_spin
    (ℏ κ : ℝ) (potential : SchwartzSpinor1D.Spatial)
    (internalH : SchwartzSpinor1D.SpinMatrix) (axis : SchwartzSpinor1D.SpinAxis) :
    (schwartzSpinCurrentRepresentation1D ℏ κ potential internalH axis).currentDensity =
      (SchwartzSpinor1D.velocityOperator ℏ κ).comp
        (SchwartzSpinor1D.spinOperator ℏ axis) := by
  rw [schwartzSpinCurrentRepresentation1D_currentDensity]
  exact symmetrizedSpinCurrent_eq_velocity_comp_spin ℏ κ axis

/-- The spin commutator of the full Hamiltonian is entirely the commutator with the internal
Hamiltonian matrix. -/
theorem linearCommutator_schwartzSpinorHamiltonian_spinOperator
    (κ : ℝ) (potential : SchwartzSpinor1D.Spatial)
    (internalH : SchwartzSpinor1D.SpinMatrix)
    (ℏ : ℝ) (axis : SchwartzSpinor1D.SpinAxis) :
    _root_.ConservationLaw.linearCommutator
        (SchwartzSpinor1D.hamiltonian κ potential internalH)
        (SchwartzSpinor1D.spinOperator ℏ axis) =
      _root_.ConservationLaw.linearCommutator
        (SchwartzSpinor1D.internalOperator internalH)
        (SchwartzSpinor1D.spinOperator ℏ axis) := by
  exact SchwartzSpinor1D.hamiltonian_spin_commutator_eq_internal
    κ potential internalH ℏ axis

/-- The canonical localized spin source/torque is generated only by the internal Hamiltonian
commutator `[H_internal,S_a]`. -/
theorem schwartzSpin_sourceCommutator_eq_internal
    (κ : ℝ) (potential : SchwartzSpinor1D.Spatial)
    (internalH : SchwartzSpinor1D.SpinMatrix)
    (ℏ : ℝ) (axis : SchwartzSpinor1D.SpinAxis) (f : SchwartzSpinor1D.Spatial) :
    _root_.ConservationLaw.sourceCommutator SchwartzSpinorOneParticle1D
        (SchwartzSpinor1D.hamiltonian κ potential internalH)
        SchwartzSpinor1D.multiplicationLinear
        (SchwartzSpinor1D.spinOperator ℏ axis) f =
      _root_.ConservationLaw.symmetrizedProduct
        (SchwartzSpinor1D.multiplicationOperator f)
        (_root_.ConservationLaw.linearCommutator
          (SchwartzSpinor1D.internalOperator internalH)
          (SchwartzSpinor1D.spinOperator ℏ axis)) := by
  rw [_root_.ConservationLaw.sourceCommutator]
  rw [linearCommutator_schwartzSpinorHamiltonian_spinOperator]
  rfl

/-- If the internal Hamiltonian conserves the selected spin component, the local spin source
vanishes and the balance law reduces to pure transport. -/
theorem schwartzSpin_sourceCommutator_eq_zero_of_internal_commutes
    (κ : ℝ) (potential : SchwartzSpinor1D.Spatial)
    (internalH : SchwartzSpinor1D.SpinMatrix)
    (ℏ : ℝ) (axis : SchwartzSpinor1D.SpinAxis) (f : SchwartzSpinor1D.Spatial)
    (hcomm : _root_.ConservationLaw.linearCommutator
      (SchwartzSpinor1D.internalOperator internalH)
      (SchwartzSpinor1D.spinOperator ℏ axis) = 0) :
    _root_.ConservationLaw.sourceCommutator SchwartzSpinorOneParticle1D
        (SchwartzSpinor1D.hamiltonian κ potential internalH)
        SchwartzSpinor1D.multiplicationLinear
        (SchwartzSpinor1D.spinOperator ℏ axis) f = 0 := by
  rw [schwartzSpin_sourceCommutator_eq_internal]
  simp [hcomm]

end
end Continuum
end SingleParticle
end QuantumMechanics
