import LeanCondensedMatter.SecondQuantization.Fermionic.Diagrammatics.TwoPointDiagramExpansion.FiberVacuumPairEmbedding
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.TwoPoint.SlotSplitVacuumComponents

set_option linter.style.header false

/-!
# Image of the fixed-order vacuum pair embedding

The normalized-pair embedding of `FiberVacuumPairEmbedding` lands on the quartic right side of the
canonical slot split.  This module identifies the full ambient component of every embedded pair as a
vacuum component and packages the embedding with that codomain.  The remaining image theorem is
therefore only surjectivity onto ambient vacuum-component pairs.
-/

namespace SecondQuantization
namespace Fermionic

open Combinatorics

variable {Mode : Type*} {n : ℕ} {i j : Mode}

/-- Normalized mixed-time pairs whose full ambient component is a vacuum component. -/
abbrev FixedExternalTwoPointWickDiagram.MixedVacuumPair
    (d : FixedExternalTwoPointWickDiagram Mode n i j)
    (τ τ' : ℝ) (σ : Fin n → ℝ) :=
  {pr : (d.pairingInMixedOrder τ τ' σ).NormalizedPair //
    d.mixedPairComponent τ τ' σ pr ∈ d.1.vacuumComponentParts}

/-- The first endpoint of an embedded fixed-order quartic vacuum pair lies in the ambient component
generated by the corresponding right-side quartic vertex. -/
theorem fixedExternalOfSlotSplitVacuumNormalizedPairEmbedding_component
    (T : Finset (Fin n))
    (ext : FixedExternalTwoPointWickDiagramOn Mode n T i j)
    (vac : QuarticWickDiagram Mode n ((Finset.univ : Finset (Fin n)) \ T))
    (τ τ' : ℝ) (σ : Fin n → ℝ)
    (hσ : StrictAnti (σ ∘ fixedExternalVacuumSlot T))
    (pr : (vac.pairingInOrder (fixedExternalVacuumOrder T)).NormalizedPair) :
    let d := fixedExternalOfSlotSplit T ext vac
    let q := Common.orderedLegToDiagramLeg
      ((Finset.univ : Finset (Fin n)) \ T) (fixedExternalVacuumOrder T) pr.1.1
    d.mixedPairComponent τ τ' σ
        (fixedExternalOfSlotSplitVacuumNormalizedPairEmbedding T ext vac τ τ' σ hσ pr) =
      ⟨d.1.componentBlock (Common.slotSplitVacuumVertex (Common.vertexOfLeg q)),
        d.1.componentBlock_mem_componentPartition
          (Common.slotSplitVacuumVertex (Common.vertexOfLeg q))⟩ := by
  let d := fixedExternalOfSlotSplit T ext vac
  let p := pr.1.1
  let q := Common.orderedLegToDiagramLeg
    ((Finset.univ : Finset (Fin n)) \ T) (fixedExternalVacuumOrder T) p
  have hleg :
      mixedTimeAmbientPositionEquiv τ τ' σ
          (mixedTimeOrderedQuarticLegMapPosition
            (fixedExternalVacuumSlot T) τ τ' σ p) =
        Common.slotLegSplitting (Finset.subset_univ T) (Sum.inr q) := by
    apply (Common.twoPointLegEquiv (Finset.univ : Finset (Fin n))).injective
    rw [twoPointLegEquiv_mixedTimeAmbientPositionEquiv]
    change mixedTimeOrderedAtomicLegEquiv τ τ' σ
        (mixedTimeOrderedAtomicLegPosition τ τ' σ
          (orderedQuarticLegMapToTwoPointLeg (fixedExternalVacuumSlot T) p)) = _
    rw [mixedTimeOrderedAtomicLegEquiv_mixedTimeOrderedAtomicLegPosition]
    calc
      orderedQuarticLegMapToTwoPointLeg (fixedExternalVacuumSlot T) p =
          (Common.twoPointLegEquiv (Finset.univ : Finset (Fin n)))
            ((Common.twoPointLegEquiv (Finset.univ : Finset (Fin n))).symm
              (orderedQuarticLegMapToTwoPointLeg (fixedExternalVacuumSlot T) p)) := by
        rw [Equiv.apply_symm_apply]
      _ = (Common.twoPointLegEquiv (Finset.univ : Finset (Fin n)))
          (Common.slotLegSplitting (Finset.subset_univ T) (Sum.inr q)) := by
        exact congrArg (Common.twoPointLegEquiv (Finset.univ : Finset (Fin n)))
          (by simpa [q] using fixedExternalVacuumOrderedLeg_eq_slotSplitRight T p)
  have hvertex :
      Common.twoPointVertexOfLeg
          (mixedTimeAmbientPositionEquiv τ τ' σ
            (mixedTimeOrderedQuarticLegMapPosition
              (fixedExternalVacuumSlot T) τ τ' σ p)) =
        Common.slotSplitVacuumVertex (Common.vertexOfLeg q) := by
    rw [hleg, Common.twoPointVertexOfLeg_slotLegSplitting_inr_exact]
  apply Subtype.ext
  change d.1.componentBlock
      (Common.twoPointVertexOfLeg
        (mixedTimeAmbientPositionEquiv τ τ' σ
          (fixedExternalOfSlotSplitVacuumNormalizedPairEmbedding
            T ext vac τ τ' σ hσ pr).1.1)) = _
  rw [fixedExternalOfSlotSplitVacuumNormalizedPairEmbedding_apply]
  exact congrArg d.1.componentBlock hvertex

/-- Every normalized pair coming from the standalone quartic vacuum piece belongs to an ambient
vacuum component after reassembly. -/
theorem fixedExternalOfSlotSplitVacuumNormalizedPairEmbedding_mem_vacuumComponentParts
    (T : Finset (Fin n))
    (ext : FixedExternalTwoPointWickDiagramOn Mode n T i j)
    (vac : QuarticWickDiagram Mode n ((Finset.univ : Finset (Fin n)) \ T))
    (τ τ' : ℝ) (σ : Fin n → ℝ)
    (hσ : StrictAnti (σ ∘ fixedExternalVacuumSlot T))
    (pr : (vac.pairingInOrder (fixedExternalVacuumOrder T)).NormalizedPair) :
    let d := fixedExternalOfSlotSplit T ext vac
    d.mixedPairComponent τ τ' σ
        (fixedExternalOfSlotSplitVacuumNormalizedPairEmbedding T ext vac τ τ' σ hσ pr) ∈
      d.1.vacuumComponentParts := by
  let d := fixedExternalOfSlotSplit T ext vac
  let q := Common.orderedLegToDiagramLeg
    ((Finset.univ : Finset (Fin n)) \ T) (fixedExternalVacuumOrder T) pr.1.1
  change d.mixedPairComponent τ τ' σ
      (fixedExternalOfSlotSplitVacuumNormalizedPairEmbedding T ext vac τ τ' σ hσ pr) ∈
    d.1.vacuumComponentParts
  rw [fixedExternalOfSlotSplitVacuumNormalizedPairEmbedding_component
    T ext vac τ τ' σ hσ pr]
  exact Common.componentBlock_slotSplitVacuumVertex_mem_vacuumComponentParts
    (Finset.subset_univ T) ext.1 vac (Common.vertexOfLeg q)

/-- The fixed-order quartic normalized-pair embedding, with codomain restricted to ambient vacuum
component pairs. -/
noncomputable def fixedExternalOfSlotSplitVacuumMixedPairEmbedding
    (T : Finset (Fin n))
    (ext : FixedExternalTwoPointWickDiagramOn Mode n T i j)
    (vac : QuarticWickDiagram Mode n ((Finset.univ : Finset (Fin n)) \ T))
    (τ τ' : ℝ) (σ : Fin n → ℝ)
    (hσ : StrictAnti (σ ∘ fixedExternalVacuumSlot T)) :
    (vac.pairingInOrder (fixedExternalVacuumOrder T)).NormalizedPair ↪
      (fixedExternalOfSlotSplit T ext vac).MixedVacuumPair τ τ' σ where
  toFun pr :=
    ⟨fixedExternalOfSlotSplitVacuumNormalizedPairEmbedding T ext vac τ τ' σ hσ pr,
      fixedExternalOfSlotSplitVacuumNormalizedPairEmbedding_mem_vacuumComponentParts
        T ext vac τ τ' σ hσ pr⟩
  inj' := by
    intro p q hpq
    apply (fixedExternalOfSlotSplitVacuumNormalizedPairEmbedding
      T ext vac τ τ' σ hσ).injective
    exact congrArg Subtype.val hpq

@[simp]
theorem fixedExternalOfSlotSplitVacuumMixedPairEmbedding_apply
    (T : Finset (Fin n))
    (ext : FixedExternalTwoPointWickDiagramOn Mode n T i j)
    (vac : QuarticWickDiagram Mode n ((Finset.univ : Finset (Fin n)) \ T))
    (τ τ' : ℝ) (σ : Fin n → ℝ)
    (hσ : StrictAnti (σ ∘ fixedExternalVacuumSlot T))
    (pr : (vac.pairingInOrder (fixedExternalVacuumOrder T)).NormalizedPair) :
    (fixedExternalOfSlotSplitVacuumMixedPairEmbedding
      T ext vac τ τ' σ hσ pr).1 =
      fixedExternalOfSlotSplitVacuumNormalizedPairEmbedding T ext vac τ τ' σ hσ pr :=
  rfl

end Fermionic
end SecondQuantization
