import LeanCondensedMatter.SecondQuantization.Fermionic.Diagrammatics.TwoPointDiagramExpansion.FiberVacuumPrefactor
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.TwoPoint.SlotSplitVacuumPairing
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.TwoPoint.MixedComponentPairEquiv
import LeanCondensedMatter.SecondQuantization.Common.Diagrammatics.TwoPoint.SlotSplitVacuumComponents

set_option linter.style.header false

/-!
# Image of the fixed-order vacuum pair embedding

The Common-owned normalized-pair embedding lands on the quartic right side of the canonical slot
split. This module identifies the full ambient component of every embedded pair as a vacuum
component and then proves that every ambient vacuum-component pair occurs this way.

Surjectivity is obtained by finite cardinality rather than by reconstructing endpoints individually:
ambient vacuum pairs are the dependent sum of the Common-owned mixed pair fibers of the vacuum
components; those fibers have twice the corresponding interaction-component cardinality; and
`slotSplitVacuumComponentEquiv` identifies the sum of those cardinalities with the full quartic
vacuum vertex set.
-/

namespace SecondQuantization
namespace Fermionic

open Combinatorics
open Common

variable {Mode : Type*} {n : ℕ} {i j : Mode}

/-- Normalized mixed-time pairs whose full ambient component is a vacuum component. -/
abbrev FixedExternalTwoPointWickDiagram.MixedVacuumPair
    (d : FixedExternalTwoPointWickDiagram Mode n i j)
    (τ τ' : ℝ) (σ : Fin n → ℝ) :=
  {pr : (d.1.pairingInMixedOrder τ τ' σ).NormalizedPair //
    d.1.mixedPairComponent τ τ' σ pr ∈ d.1.vacuumComponentParts}

/-- The first endpoint of an embedded fixed-order quartic vacuum pair lies in the ambient component
generated by the corresponding right-side quartic vertex. -/
theorem fixedExternalOfSlotSplitVacuumNormalizedPairEmbedding_component
    (T : Finset (Fin n))
    (ext : FixedExternalTwoPointWickDiagramOn Mode n T i j)
    (vac : QuarticWickDiagram Mode n ((Finset.univ : Finset (Fin n)) \ T))
    (τ τ' : ℝ) (σ : Fin n → ℝ)
    (hσ : StrictAnti (σ ∘ slotSplitVacuumSlot T))
    (pr : (vac.pairingInOrder (slotSplitVacuumOrder T)).NormalizedPair) :
    let d := fixedExternalOfSlotSplit T ext vac
    let q := Common.orderedLegToDiagramLeg
      ((Finset.univ : Finset (Fin n)) \ T) (slotSplitVacuumOrder T) pr.1.1
    d.1.mixedPairComponent τ τ' σ
        (Common.TwoPointDiagram.slotSplitVacuumNormalizedPairEmbedding
          T ext.1 vac τ τ' σ hσ pr) =
      ⟨d.1.componentBlock (Common.slotSplitVacuumVertex (Common.vertexOfLeg q)),
        d.1.componentBlock_mem_componentPartition
          (Common.slotSplitVacuumVertex (Common.vertexOfLeg q))⟩ := by
  let d := fixedExternalOfSlotSplit T ext vac
  let p := pr.1.1
  let q := Common.orderedLegToDiagramLeg
    ((Finset.univ : Finset (Fin n)) \ T) (slotSplitVacuumOrder T) p
  have hleg :
      mixedTimeAmbientPositionEquiv τ τ' σ
          (mixedTimeOrderedQuarticLegMapPosition
            (slotSplitVacuumSlot T) τ τ' σ p) =
        Common.slotLegSplitting (Finset.subset_univ T) (Sum.inr q) := by
    apply (Common.twoPointLegEquiv (Finset.univ : Finset (Fin n))).injective
    rw [twoPointLegEquiv_mixedTimeAmbientPositionEquiv]
    change mixedTimeOrderedAtomicLegEquiv τ τ' σ
        (mixedTimeOrderedAtomicLegPosition τ τ' σ
          (orderedQuarticLegMapToTwoPointLeg (slotSplitVacuumSlot T) p)) = _
    rw [mixedTimeOrderedAtomicLegEquiv_mixedTimeOrderedAtomicLegPosition]
    calc
      orderedQuarticLegMapToTwoPointLeg (slotSplitVacuumSlot T) p =
          (Common.twoPointLegEquiv (Finset.univ : Finset (Fin n)))
            ((Common.twoPointLegEquiv (Finset.univ : Finset (Fin n))).symm
              (orderedQuarticLegMapToTwoPointLeg (slotSplitVacuumSlot T) p)) := by
        rw [Equiv.apply_symm_apply]
      _ = (Common.twoPointLegEquiv (Finset.univ : Finset (Fin n)))
          (Common.slotLegSplitting (Finset.subset_univ T) (Sum.inr q)) := by
        exact congrArg (Common.twoPointLegEquiv (Finset.univ : Finset (Fin n)))
          (by simpa [q] using slotSplitVacuumOrderedLeg_eq_slotSplitRight T p)
  have hvertex :
      Common.twoPointVertexOfLeg
          (mixedTimeAmbientPositionEquiv τ τ' σ
            (mixedTimeOrderedQuarticLegMapPosition
              (slotSplitVacuumSlot T) τ τ' σ p)) =
        Common.slotSplitVacuumVertex (Common.vertexOfLeg q) := by
    rw [hleg, Common.twoPointVertexOfLeg_slotLegSplitting_inr_exact]
  apply Subtype.ext
  change d.1.componentBlock
      (Common.twoPointVertexOfLeg
        (mixedTimeAmbientPositionEquiv τ τ' σ
          (Common.TwoPointDiagram.slotSplitVacuumNormalizedPairEmbedding
            T ext.1 vac τ τ' σ hσ pr).1.1)) = _
  rw [Common.TwoPointDiagram.slotSplitVacuumNormalizedPairEmbedding_apply]
  exact congrArg d.1.componentBlock hvertex

/-- Every normalized pair coming from the standalone quartic vacuum piece belongs to an ambient
vacuum component after reassembly. -/
theorem fixedExternalOfSlotSplitVacuumNormalizedPairEmbedding_mem_vacuumComponentParts
    (T : Finset (Fin n))
    (ext : FixedExternalTwoPointWickDiagramOn Mode n T i j)
    (vac : QuarticWickDiagram Mode n ((Finset.univ : Finset (Fin n)) \ T))
    (τ τ' : ℝ) (σ : Fin n → ℝ)
    (hσ : StrictAnti (σ ∘ slotSplitVacuumSlot T))
    (pr : (vac.pairingInOrder (slotSplitVacuumOrder T)).NormalizedPair) :
    let d := fixedExternalOfSlotSplit T ext vac
    d.1.mixedPairComponent τ τ' σ
        (Common.TwoPointDiagram.slotSplitVacuumNormalizedPairEmbedding
          T ext.1 vac τ τ' σ hσ pr) ∈
      d.1.vacuumComponentParts := by
  let d := fixedExternalOfSlotSplit T ext vac
  let q := Common.orderedLegToDiagramLeg
    ((Finset.univ : Finset (Fin n)) \ T) (slotSplitVacuumOrder T) pr.1.1
  change d.1.mixedPairComponent τ τ' σ
      (Common.TwoPointDiagram.slotSplitVacuumNormalizedPairEmbedding
        T ext.1 vac τ τ' σ hσ pr) ∈
    d.1.vacuumComponentParts
  rw [fixedExternalOfSlotSplitVacuumNormalizedPairEmbedding_component
    T ext vac τ τ' σ hσ pr]
  exact Common.componentBlock_slotSplitVacuumVertex_mem_vacuumComponentParts
    (Finset.subset_univ T) ext.1 vac (Common.vertexOfLeg q)

/-- The fixed-order quartic normalized-pair embedding, with codomain restricted to ambient vacuum
component pairs. -/
noncomputable def fixedExternalOfSlotSplitVacuumMixedPairEmbedding
    (T : Finset (Fin n))
    (ext : FixedExternalTwoPointWickDiagramOn Mode n T i j)
    (vac : QuarticWickDiagram Mode n ((Finset.univ : Finset (Fin n)) \ T))
    (τ τ' : ℝ) (σ : Fin n → ℝ)
    (hσ : StrictAnti (σ ∘ slotSplitVacuumSlot T)) :
    (vac.pairingInOrder (slotSplitVacuumOrder T)).NormalizedPair ↪
      (fixedExternalOfSlotSplit T ext vac).MixedVacuumPair τ τ' σ where
  toFun pr :=
    ⟨Common.TwoPointDiagram.slotSplitVacuumNormalizedPairEmbedding
        T ext.1 vac τ τ' σ hσ pr,
      fixedExternalOfSlotSplitVacuumNormalizedPairEmbedding_mem_vacuumComponentParts
        T ext vac τ τ' σ hσ pr⟩
  inj' := by
    intro p q hpq
    apply (Common.TwoPointDiagram.slotSplitVacuumNormalizedPairEmbedding
      T ext.1 vac τ τ' σ hσ).injective
    exact congrArg Subtype.val hpq

@[simp]
theorem fixedExternalOfSlotSplitVacuumMixedPairEmbedding_apply
    (T : Finset (Fin n))
    (ext : FixedExternalTwoPointWickDiagramOn Mode n T i j)
    (vac : QuarticWickDiagram Mode n ((Finset.univ : Finset (Fin n)) \ T))
    (τ τ' : ℝ) (σ : Fin n → ℝ)
    (hσ : StrictAnti (σ ∘ slotSplitVacuumSlot T))
    (pr : (vac.pairingInOrder (slotSplitVacuumOrder T)).NormalizedPair) :
    (fixedExternalOfSlotSplitVacuumMixedPairEmbedding
      T ext vac τ τ' σ hσ pr).1 =
      Common.TwoPointDiagram.slotSplitVacuumNormalizedPairEmbedding
        T ext.1 vac τ τ' σ hσ pr :=
  rfl

/-- Ambient mixed vacuum pairs are the dependent disjoint union of the mixed pair fibers of the
ambient vacuum components. -/
noncomputable def FixedExternalTwoPointWickDiagram.mixedVacuumPairSigmaEquiv
    (d : FixedExternalTwoPointWickDiagram Mode n i j)
    (τ τ' : ℝ) (σ : Fin n → ℝ) :
    (Σ B : ↥d.1.vacuumComponentParts, d.1.MixedComponentPair τ τ' σ B.1) ≃
      d.MixedVacuumPair τ τ' σ where
  toFun x :=
    ⟨x.2.1, by
      rw [x.2.2]
      exact x.1.2⟩
  invFun pr :=
    ⟨⟨d.1.mixedPairComponent τ τ' σ pr.1, pr.2⟩, ⟨pr.1, rfl⟩⟩
  left_inv := by
    rintro ⟨B, pr⟩
    let B' : ↥d.1.vacuumComponentParts :=
      ⟨d.1.mixedPairComponent τ τ' σ pr.1, by
        rw [pr.2]
        exact B.2⟩
    have hB : B' = B := by
      apply Subtype.ext
      exact pr.2
    apply Sigma.ext hB
    refine (Subtype.heq_iff_coe_eq ?_).2 ?_
    · intro x
      change d.1.mixedPairComponent τ τ' σ x = B'.1 ↔
        d.1.mixedPairComponent τ τ' σ x = B.1
      rw [hB]
    · rfl
  right_inv _ := rfl

/-- One ambient vacuum-component mixed pair fiber has twice as many elements as interaction vertices
in that component. -/
theorem FixedExternalTwoPointWickDiagram.card_mixedVacuumComponentPair
    (d : FixedExternalTwoPointWickDiagram Mode n i j)
    (τ τ' : ℝ) (σ : Fin n → ℝ) (B : ↥d.1.vacuumComponentParts) :
    Fintype.card (d.1.MixedComponentPair τ τ' σ B.1) =
      2 * (Common.TwoPointDiagram.interactionPart
        (B.1 : Finset (Common.TwoPointVertex (Finset.univ : Finset (Fin n))))).card := by
  let hVac : d.1.ComponentIsVacuum B.1 :=
    (d.1.mem_vacuumComponentParts B.1).1 B.2
  rw [Fintype.card_congr (d.1.mixedVacuumComponentPairEquiv τ τ' σ B.1 hVac)]
  simpa using (d.1.restrictedVacuumPairing B.1 hVac).card_normalizedPair

/-- For an externally connected left piece, the ambient vacuum components contain exactly the
interaction vertices of the standalone quartic right piece. -/
theorem fixedExternalOfSlotSplit_sum_vacuumComponentInteractionCard
    (T : Finset (Fin n))
    (ext : FixedExternalTwoPointWickDiagramOn Mode n T i j)
    (vac : QuarticWickDiagram Mode n ((Finset.univ : Finset (Fin n)) \ T))
    (hext : ext.1.IsExternallyConnected) :
    let d := fixedExternalOfSlotSplit T ext vac
    (∑ B : ↥d.1.vacuumComponentParts,
      (Common.TwoPointDiagram.interactionPart
        (B.1 : Finset (Common.TwoPointVertex (Finset.univ : Finset (Fin n))))).card) =
      ((Finset.univ : Finset (Fin n)) \ T).card := by
  let d := fixedExternalOfSlotSplit T ext vac
  let e := Common.slotSplitVacuumComponentEquiv
    (Finset.subset_univ T) ext.1 vac hext
  let F : ↥d.1.vacuumComponentParts → ℕ := fun B =>
    (Common.TwoPointDiagram.interactionPart
      (B.1 : Finset (Common.TwoPointVertex (Finset.univ : Finset (Fin n))))).card
  change (∑ B : ↥d.1.vacuumComponentParts, F B) = _
  calc
    (∑ B : ↥d.1.vacuumComponentParts, F B) =
        ∑ C : vac.componentPartition.parts, F (e C) :=
      (Equiv.sum_comp e F).symm
    _ = ∑ C : vac.componentPartition.parts, (C : Finset (Fin n)).card := by
      apply Fintype.sum_congr
      intro C
      change (Common.TwoPointDiagram.interactionPart
          ((e C).1.1 : Finset (Common.TwoPointVertex
            (Finset.univ : Finset (Fin n))))).card = _
      rw [Common.slotSplitVacuumComponentEquiv_apply,
        Common.interactionPart_slotSplitVacuumComponentPart]
    _ = ((Finset.univ : Finset (Fin n)) \ T).card := by
      rw [Finset.sum_coe_sort]
      exact vac.componentPartition.sum_card_parts

/-- The type of all ambient mixed vacuum pairs has the same cardinality as the normalized pairs of
the standalone quartic vacuum pairing. -/
theorem fixedExternalOfSlotSplit_card_mixedVacuumPair
    (T : Finset (Fin n))
    (ext : FixedExternalTwoPointWickDiagramOn Mode n T i j)
    (vac : QuarticWickDiagram Mode n ((Finset.univ : Finset (Fin n)) \ T))
    (hext : ext.1.IsExternallyConnected)
    (τ τ' : ℝ) (σ : Fin n → ℝ) :
    Fintype.card ((fixedExternalOfSlotSplit T ext vac).MixedVacuumPair τ τ' σ) =
      2 * ((Finset.univ : Finset (Fin n)) \ T).card := by
  let d := fixedExternalOfSlotSplit T ext vac
  rw [← Fintype.card_congr (d.mixedVacuumPairSigmaEquiv τ τ' σ), Fintype.card_sigma]
  simp_rw [d.card_mixedVacuumComponentPair τ τ' σ]
  rw [← Finset.mul_sum]
  exact congrArg (2 * ·)
    (fixedExternalOfSlotSplit_sum_vacuumComponentInteractionCard T ext vac hext)

/-- Under external connectedness, every ambient mixed pair lying in a vacuum component comes from a
unique normalized pair of the standalone quartic vacuum pairing. -/
theorem fixedExternalOfSlotSplitVacuumMixedPairEmbedding_surjective
    (T : Finset (Fin n))
    (ext : FixedExternalTwoPointWickDiagramOn Mode n T i j)
    (vac : QuarticWickDiagram Mode n ((Finset.univ : Finset (Fin n)) \ T))
    (hext : ext.1.IsExternallyConnected)
    (τ τ' : ℝ) (σ : Fin n → ℝ)
    (hσ : StrictAnti (σ ∘ slotSplitVacuumSlot T)) :
    Function.Surjective
      (fixedExternalOfSlotSplitVacuumMixedPairEmbedding T ext vac τ τ' σ hσ) := by
  let emb := fixedExternalOfSlotSplitVacuumMixedPairEmbedding T ext vac τ τ' σ hσ
  have hsource :
      Fintype.card (vac.pairingInOrder (slotSplitVacuumOrder T)).NormalizedPair =
        2 * ((Finset.univ : Finset (Fin n)) \ T).card := by
    simpa using (vac.pairingInOrder (slotSplitVacuumOrder T)).card_normalizedPair
  have htarget :
      Fintype.card ((fixedExternalOfSlotSplit T ext vac).MixedVacuumPair τ τ' σ) =
        2 * ((Finset.univ : Finset (Fin n)) \ T).card :=
    fixedExternalOfSlotSplit_card_mixedVacuumPair T ext vac hext τ τ' σ
  have hbij : Function.Bijective emb :=
    (Fintype.bijective_iff_injective_and_card emb).2
      ⟨emb.injective, hsource.trans htarget.symm⟩
  exact hbij.2

/-- The fixed-order quartic vacuum normalized pairs are equivalent to all ambient mixed normalized
pairs carried by vacuum components. -/
noncomputable def fixedExternalOfSlotSplitVacuumMixedPairEquiv
    (T : Finset (Fin n))
    (ext : FixedExternalTwoPointWickDiagramOn Mode n T i j)
    (vac : QuarticWickDiagram Mode n ((Finset.univ : Finset (Fin n)) \ T))
    (hext : ext.1.IsExternallyConnected)
    (τ τ' : ℝ) (σ : Fin n → ℝ)
    (hσ : StrictAnti (σ ∘ slotSplitVacuumSlot T)) :
    (vac.pairingInOrder (slotSplitVacuumOrder T)).NormalizedPair ≃
      (fixedExternalOfSlotSplit T ext vac).MixedVacuumPair τ τ' σ :=
  Equiv.ofBijective (fixedExternalOfSlotSplitVacuumMixedPairEmbedding T ext vac τ τ' σ hσ)
    ⟨(fixedExternalOfSlotSplitVacuumMixedPairEmbedding T ext vac τ τ' σ hσ).injective,
      fixedExternalOfSlotSplitVacuumMixedPairEmbedding_surjective
        T ext vac hext τ τ' σ hσ⟩

@[simp]
theorem fixedExternalOfSlotSplitVacuumMixedPairEquiv_apply
    (T : Finset (Fin n))
    (ext : FixedExternalTwoPointWickDiagramOn Mode n T i j)
    (vac : QuarticWickDiagram Mode n ((Finset.univ : Finset (Fin n)) \ T))
    (hext : ext.1.IsExternallyConnected)
    (τ τ' : ℝ) (σ : Fin n → ℝ)
    (hσ : StrictAnti (σ ∘ slotSplitVacuumSlot T))
    (pr : (vac.pairingInOrder (slotSplitVacuumOrder T)).NormalizedPair) :
    (fixedExternalOfSlotSplitVacuumMixedPairEquiv T ext vac hext τ τ' σ hσ pr).1 =
      Common.TwoPointDiagram.slotSplitVacuumNormalizedPairEmbedding
        T ext.1 vac τ τ' σ hσ pr :=
  rfl

end Fermionic
end SecondQuantization
