import LeanCondensedMatter.Transport.Models.MassiveDirac.Streda
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDirac.Bastin.Berry
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDirac.Bastin.Bands
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDirac.Bastin.Limit
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDirac.Bastin.Spectator
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDirac.Bastin.Interband
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDirac.Bastin.PoleFactor
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDirac.Bastin.PoleWindow
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDirac.Bastin.PoleContinuity
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDirac.Bastin.PoleWindowBound
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDirac.Bastin.PoleExtraction
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDirac.Bastin.PairIntegral
import LeanCondensedMatter.Transport.Models.MassiveDirac.Bastin.PairBerry
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDirac.Bastin.RadialDomination
import LeanCondensedMatter.Transport.Models.MassiveDirac.Bastin.RadialSpectatorBound
import LeanCondensedMatter.Transport.Models.MassiveDirac.Bastin.RadialSpectatorUniformBound
import LeanCondensedMatter.Transport.Models.MassiveDirac.Bastin.RadialPairUniformBound
import LeanCondensedMatter.Transport.Models.MassiveDirac.Bastin.RadialDominatedConvergence
import LeanCondensedMatter.Transport.Models.MassiveDirac.Bastin.RadialEnergyBridge
import LeanCondensedMatter.Transport.Models.MassiveDirac.Bastin.ZeroTemperaturePair
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDirac.Bastin.CleanConductivity

set_option linter.style.header false

/-!
# Massive-Dirac Bastin analysis

Public umbrella for the concrete massive-Dirac finite/zero-broadening Bastin proof chain. Canonical
implementations live under `MassiveDirac/Bastin/`; reusable analysis is extracted upstream instead
of being re-owned here.
-/
