import LeanCondensedMatter.Transport.AnomalousHall.MassiveDirac.Streda
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinBerry
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinBands
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinLimit
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinLorentzian
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinOccupation
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinTail
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinFiniteWindow
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinFermiSurface
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinSpectator
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinInterband
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleFactor
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleWindow
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleContinuity
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleWindowContinuity
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleWindowBound
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleLocalError
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleErrorIntegral
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleInnerError
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleOuterError
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleErrorSplit
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleErrorBound
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleErrorLimit
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleExtraction
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPoleExtractionLimit
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPairIntegral
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinPairBerry
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinRadialDomination
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinRadialLimitInterchange
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinRadialSpectatorBound
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinRadialResolventBound
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinRadialSpectatorUniformBound
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinRadialPairUniformBound
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinRadialDominatedConvergence
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinRadialEnergyBridge
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinZeroTemperaturePair
import LeanCondensedMatter.Transport.AnomalousHall.MassiveDiracBastinCleanConductivity

set_option linter.style.header false

/-!
# Massive-Dirac Bastin analysis

Public umbrella for the detailed finite-broadening and zero-broadening Kubo–Bastin analysis of the
massive-Dirac anomalous-Hall benchmark: band-block decomposition, Lorentzian pole extraction,
occupation/Fermi-edge treatment, regular spectator estimates, radial dominated convergence, and the
clean finite-cutoff conductivity bridge.

This layer should shrink as reusable Lorentzian, occupation, and regular-pole extraction APIs are
moved into generic Analysis/Transport modules under #1596.
-/
