import LeanCondensedMatter.SecondQuantization.Common.Thermal.BlochDeDominicis.OperatorPeel
import LeanCondensedMatter.SecondQuantization.Bosonic.Thermal.BlochDeDominicis.OrderedProductSummable

set_option linter.style.header false

/-!
# Bosonic free-thermal operator peel

Instantiates the Common scalar-exchange peel identity for free bosonic creation/annihilation fields.
-/

namespace SecondQuantization
namespace Bosonic

open Common

noncomputable section

variable {Mode : Type*}

local instance instDecidableEqFreeThermalOperatorPeel : DecidableEq Mode := Classical.decEq Mode

/-- Bare scalar CCR contraction generated by exchanging two free thermal fields. -/
noncomputable def FreeThermalField.exchangeValue :
    FreeThermalField Mode → FreeThermalField Mode → ℂ
  | .annihilate i, .create j => if i = j then 1 else 0
  | .create i, .annihilate j => if i = j then -1 else 0
  | .annihilate _, .annihilate _ => 0
  | .create _, .create _ => 0

/-- Concrete free bosonic fields satisfy the scalar exchange relation used by the Common peel. -/
theorem FreeThermalField.operator_comp_operator_eq_exchangeValue
    (C D : FreeThermalField Mode) :
    (C.operator).comp D.operator =
      C.exchangeValue D • (LinearMap.id : FockSpace Mode →ₗ[ℂ] FockSpace Mode) +
        (D.operator).comp C.operator := by
  cases C with
  | annihilate i =>
      cases D with
      | annihilate j =>
          simpa [FreeThermalField.operator, FreeThermalField.exchangeValue] using
            (LinearMap.comp_eq_add_smul_comp_of_zetaCommutator_eq (1 : ℂ)
              (comm_annihilate_annihilate i j))
      | create j =>
          by_cases hij : i = j
          · subst j
            simpa [FreeThermalField.operator, FreeThermalField.exchangeValue] using
              (LinearMap.comp_eq_add_smul_comp_of_zetaCommutator_eq (1 : ℂ)
                (comm_annihilate_create i i))
          · simpa [FreeThermalField.operator, FreeThermalField.exchangeValue, hij] using
              (LinearMap.comp_eq_add_smul_comp_of_zetaCommutator_eq (1 : ℂ)
                (comm_annihilate_create i j))
  | create i =>
      cases D with
      | annihilate j =>
          by_cases hij : i = j
          · subst j
            simpa [FreeThermalField.operator, FreeThermalField.exchangeValue] using
              (LinearMap.comp_eq_add_smul_comp_of_zetaCommutator_eq (1 : ℂ)
                (comm_create_annihilate i i))
          · simpa [FreeThermalField.operator, FreeThermalField.exchangeValue, hij] using
              (LinearMap.comp_eq_add_smul_comp_of_zetaCommutator_eq (1 : ℂ)
                (comm_create_annihilate i j))
      | create j =>
          simpa [FreeThermalField.operator, FreeThermalField.exchangeValue] using
            (LinearMap.comp_eq_add_smul_comp_of_zetaCommutator_eq (1 : ℂ)
              (comm_create_create i j))

/-- The bosonic ordered product is the Common right-associated operator product. -/
theorem FreeThermalField.orderedProduct_eq_common_operatorProduct
    (fields : List (FreeThermalField Mode)) :
    FreeThermalField.orderedProduct fields =
      Common.BlochDeDominicis.operatorProduct FreeThermalField.operator fields := by
  induction fields with
  | nil => rfl
  | cons C t ih =>
    simp only [FreeThermalField.orderedProduct,
        Common.BlochDeDominicis.operatorProduct_cons]
    rw [ih]

/-- Bare bosonic CCR peel sum, before Gibbs/KMS rotation. -/
noncomputable def FreeThermalField.operatorPeelSum (C : FreeThermalField Mode)
    (fields : List (FreeThermalField Mode)) : FockSpace Mode →ₗ[ℂ] FockSpace Mode :=
  Common.BlochDeDominicis.operatorPeelSum FreeThermalField.operator
    FreeThermalField.exchangeValue 1 C fields

/-- Repeated CCR exchange of the first free thermal field through an arbitrary finite tail. -/
theorem FreeThermalField.operator_comp_orderedProduct_eq_operatorPeelSum
    (C : FreeThermalField Mode) (fields : List (FreeThermalField Mode)) :
    (C.operator).comp (FreeThermalField.orderedProduct fields) =
      C.operatorPeelSum fields +
        (FreeThermalField.orderedProduct fields).comp C.operator := by
  have h := Common.BlochDeDominicis.operator_comp_operatorProduct_eq_operatorPeelSum
    FreeThermalField.operator FreeThermalField.exchangeValue (1 : ℂ)
    (fun C D => by
      simpa using FreeThermalField.operator_comp_operator_eq_exchangeValue C D)
    C fields
  rw [← FreeThermalField.orderedProduct_eq_common_operatorProduct] at h
  simpa [FreeThermalField.operatorPeelSum] using h

end
end Bosonic
end SecondQuantization
